### ISSUE TITLE
Chain Sync Client: Add logging on disconnect

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1012]
It might be helpful during when the chain sync client logs why it is disconnecting. Under normal circumstnces of course users don't manually specify their upstream nodes, and so most of this behaviour is invisible, but during debugging and testnets this might help.

**Comment by edsko** [comment]
Erik writes:

thus i have two suggestions:
• a node always specify the reason it is disconnecting from the remote node
• if its because it is too far ahead, it should report the local and remove slotNo

**Comment by erikd** [comment]
One more suggestion, if the local and remote are *different* chains (eg testnet vs mainnet) that should also be reported in some way.

**Comment by edsko** [comment]
Karl writes:

The network magic is included in the version negotiation. There is no reason to drag it along inside the chainsync miniprotocol. The reason why it is possible to connect a partially synced testnet node to the mainnet is that the network magic is hardcoded to 0. https://github.com/input-output-hk/ouroboros-network/issues/1006

**Comment by mrBliss** [comment]
I thought this was already happening, see:
* To disconnect, we thrown an exception each time: https://github.com/input-output-hk/ouroboros-network/blob/9cb37e818d35b02e2fe8cbccf63a28089998513a/ouroboros-consensus/src/Ouroboros/Consensus/ChainSyncClient.hs#L524
* We use the `traceException` helper to trace it (each time): https://github.com/input-output-hk/ouroboros-network/blob/9cb37e818d35b02e2fe8cbccf63a28089998513a/ouroboros-consensus/src/Ouroboros/Consensus/ChainSyncClient.hs#L528
So as far as I know, we are tracing the necessary information. Maybe it doesn't show up in the trace because it is ignored at some point or maybe the right tracer is not enabled?
