### ISSUE TITLE
Use anachronistic ledger view in `forkBlockProduction`

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1197]

**Comment by nfrisby** [comment]
This scenario came up on my in-development branch for network outages (roughly: "network partitions"). I think I could simplify my `Property` if we introduce the invariant that a leader whose tip's slot is `s` cannot forge a valid block in a slot later than `s + 2k`.

Is that the sort of invariant this Issue intends to introduce? Glad to see it's being considered.

On the other hand, @nc6 and I had wondered if that kind of invariant would prevent legitimate behavior in a node network that was somehow "recovering" from some kind of catastrophic-ish failure.

**Comment by edsko** [comment]
Yes, that will be done, and it's essential. The current definition is just plain incorrect, we _must_ use the anachronistic ledger view:

``
        -- TODO: I think this is wrong. This uses the ledger view as it was
        -- after the last applied block. But that ledger view might have some
        -- scheduled updates which should be applied by the time we reach
        -- 'currentSlot'.
```

**Comment by nfrisby** [comment]
If I understand correctly, this bug means the node might forge an invalid block. Is that the full extent of the risk? Now that #1257 is fixed, the other nodes' ChainSync clients would refuse such a block, right?

I'm unclear on whether the node's own ChainDB would also refuse the block it just forged.

Disclaimer: My reasoning here is only from `RealPBFT`, for which the ledger view is just the active delegation map. It could be that `Praos` etc have more involved ledger views that complicate the situation -- I'm not familiar with those yet, since the current implementation artificially has no limit on anachrony so I haven't had to deal with any such failures :) yet.

**Comment by edsko** [comment]
> If I understand correctly, this bug means the node might forge an invalid block. Is that the full extent of the risk? Now that #1257 is fixed, the other nodes' ChainSync clients would refuse such a block, right?

Yes, I believe so. Although of course this then means that the node will miss its slot, which could potentially cause trouble; also, of course, if _all_ nodes do this, the chain will stop at this point, as nobody will be producing valid blocks anymore. Disaster.

> I'm unclear on whether the node's own ChainDB would also refuse the block it just forged.

The chain DB will add it it to the volatiel DB, and then when it comes to chain selection, it will disregard invalid blocks, and so it won't adopt it in the node's own chain.
