### ISSUE TITLE
Generate blocks with delegation certificates

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1202]

**Comment by edsko** [comment]
Calling this high priority because the delegation history is somewhat subtle, and _if_ we need it, it's because a core node got compromised, and so it will be quite important that delegation works correctly.

**Comment by nfrisby** [comment]
It took us a while on Slack to reach this consensus, but Edsko and Clarke got me here:

> Invariant: No two nodes ever have the same result when calculating their own `CoreNodeId`.

(For example, in PBFT a node calculates its own `CoreNodeId` by looking up the `pbftCoreNodeId` field of the `pfbtIsLeader` field of its node configuration.)

If this happens in a real net, it's operator error. For example, Duncan said we've advised operators to not use high-availability schemes because the redundancy might seem like multiple nodes claiming to be the same `CoreNodeId` and hence adversarial behavior. (E.G. One "party" forging multiple blocks in the same slot.)

So the test infrastructure should never create delegation certificates that would violate that invariant. The ledger alone can't ensure this property because different nodes on different chains could have different ledgers. The test infrastructure is the "node operator" in this case, and a good one doesn't create conflicting delegation certificates. In particular, they shut down their old node instance before they introduce the delegation certificate that enables their new node instance to lead.

The ultimate source of my confusion was that my familiarity with the code base is driven by `test-consensus`. The primary use of `CoreNodeId` there is as an identifier of distinct node instances. This is subtly different than its use in BFT and PBFT, for example, where it instead identifies the index into the sorted genesis keys of the genesis key that is currently delegated to the node. This discussion today arose because it was unclear whether `WithLeaderSchedule` should be using its `CoreNodeId`s as an index into the genesis keys or as an identifier of a node instance. Without generating delegation certificates those are the same thing (assuming the at-genesis test setup is total and correct -- c.f. #916). With generating certs and also the above invariant, they are still the same.

**Comment by nfrisby** [comment]
One follow-up: PR 1419 (the one that closed this Issue) did so-called _heavyweight delegation_. I'm still fuzzy on the distinction vs _lightweight_ (at least how it would manifest in the code), but I essentially inherited the heavyweight approach from what the `RealPBFT` test looked like before this PR. We didn't think to do so, but perhaps it would have been worthwhile to consider lightweight as well/instead.

In particular, should this Issue be replicated: this one for _heavyweight delegation_ and another for _lightweight delegation_? cc: @mrBliss @edsko

**Comment by edsko** [comment]
I always get so confused about this. Let's clear this up with @dcoutts .

**Comment by edsko** [comment]
What we're testing here is right: this weird "dual" approach where we have a certificate when producing a block ("lightweight") _and_ post a certificate to the chain ("heavyweight") is just one of those weird artifacts of the Byron ledger. This will be different in Shelley, but as far as testing Byron is concerned, this suffices.
