### ISSUE TITLE
Avoid copying bytestrings when slicing annotations

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1215]
When decoding a Byron block, we fill in the strict bytestring annotations by slicing the lazy input bytestring and converting each slice into a strict bytestring, which requires copying the bytestring (*O(n)*), see: https://github.com/input-output-hk/ouroboros-network/blob/ba34ca34293cc4198eb1f587c0b3275ce8409191/ouroboros-consensus/src/Ouroboros/Consensus/Ledger/Byron/Block.hs#L218

We are forced to do this conversion because `Annotated` in `cardano-binary` wants annotations to be strict bytestrings, see:
https://github.com/input-output-hk/cardano-base/blob/47b85629e2bb5568e3174afd6b9c2fea8cb682e4/binary/src/Cardano/Binary/Annotated.hs#L89

If that strict bytestring were changed to a lazy bytestring, we can avoid all this needless copying.

Note that slicing a lazy bytestring is *O(c)*, not *O(n/c)*, as documented in its API. So in practice, slicing a lazy bytestring is not that much more expensive than slicing a strict one (*O(1)*).

An important advantage of using a lazy bytestring over a strict bytestring is that sliced bytestrings will only hold on to the chunk of the lazy bytestring they refer to, instead of holding on to the whole strict bytestring. Another advantage over strict bytestrings is that the latter require a contiguous segment of memory, whereas the former can consists of multiple chunks.

**Comment by lehins** [comment]
It is better to use strict ByteString for annotations, because:

1. The most common reason (if not the only reason) for preserving the bytes is to enforce cryptographic integrity by the means of hashing the bytes that were received over the wire. Well, in order to hash those bytes we need to convert it to a strict ByteString. So, any time we deserialize a type, like block, or transaction we'll have to hash it, sometimes multiple times. If we kept around the lazy ByteString instead of a strict one we'd have to make the copy of bytes every time when a hash of bytes is needed.
2. Default chunk size in a lazy ByteString is 32Kb, so it will require at most 2 chunks in a lazy bytestring to fit a most common Shelley block, and it will always be just one chunk for anything small like a transaction. So, using lazy ByteString only lead to higher memory overhead in practice, because one chunk is a single strict ByteString wrapped in an extra type constructor `Chunk`

I am closing this ticket, because there are at least two reasons for it:

* This ticket is concerned about `Annotated` type that was used exclusively in Byron, which is the codebase we have no plans on changing in any significant way
* It is in fact better to use strict ByteString, as I described above

Feel free to reopen the ticket, if me closing this issue is a mistake.
