### ISSUE TITLE
Ouroboros-network should be more careful about exception handling

### ISSUE THREAD

**Issue by erikd** [input-output-hk/ouroboros-network#1217]
I have just spent many hours debugging and then fixing a problem in the explorer. 

The debugging was made difficult because my code was using `panic` for things that should never happen. Unfortunately `panic` uses the exception mechanism of the GHC runtime and `network` seems to be catching all exceptions. Furthermore, exceptions that are caught to not get reported because because I am passing a `nullTracer` into `ncSubscriptionWorker_V1`.

After removing all uses of `panic` (replacing them with `Left` of an `Either` which could then printed I found that trying to call `exitFailure` (which also uses the exception system) would not actually abort the program because the exception was being caught (and silently) retried.

IMO exceptions should be avoided for anything other than:
* the impossible happened and I want to abort the program
* the `bracket` pattern where the exception is caught, resources released and the exception rethrown

If we really *must* use exceptions it should be used sparingly and precisely. If an exception is to be caught and not rethrown it should be done with great care and it should be a very small and specific subset of exceptions. In particular, it should very definitely **not** be `SomeException`.

`SomeException` includes `AsyncException` which consists of things like  `StackOverflow`, `HeapOverflow`, `ThreadKilled` and `UserInterrupt`. Other than `ThreadKilled` these should almost never be caught, especially not silently.

The use of `SomeException` [here](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-network/src/Ouroboros/Network/Subscription/Worker.hs#L462-L474) is simply wrong and needs to be fixed sooner rather than later.

My ideal solution to this would be to replace all uses of exceptions with the use of `Either` with a proper error type on the `Left`. Failing that, another solution is to replace all uses of `SomeException` with a narrower exception type that does not include `AsyncException`. I would suggest that catching anything other than `IOException` and/or a custom exception type should probably not be necessary.

**Comment by disassembler** [comment]
I think this is also why hitting ctrl-c in docker container doesn't terminate.

**Comment by erikd** [comment]
@disassembler Yes, that is **exactly** why that is not working! Control-C is `UserInterrupt`.

**Comment by avieth** [comment]
This is quite a broad ticket. From the discussion on slack it looks like Erik has uncovered at least one part of this repository which, without controversy, *does not do the right thing* (it squelches async exceptions). Indeed that's probably

> also why hitting ctrl-c in docker container doesn't terminate.

Indeed

> The use of SomeException here is simply wrong and needs to be fixed sooner rather than later.

This ought to and will be fixed. And that should be the end of this ticket.

**Comment by erikd** [comment]
> This is quite a broad ticket.

Hopefully that breadth will get people thinking a bit more carefully about if, when and how to use exceptions.

Replacing the current use of `SomeException` with a much narrower set of exceptions (which specifically allows functions like `exitFailure` and Control-C to kill the program) would be an acceptable solution.

**Comment by mrBliss** [comment]
@coot Won't #1127 fix this?

**Comment by coot** [comment]
@erikd I'd argue that the `SomeException` here is not a problem, since this is in a connection thread and if there was any exception (either durring `connect` or while running an aplication, or an async exception) the thread will terminate.

#1127 will not fix this, but it will allow to kill the subscription worker (e.g. outbound connections) and server (inbound connections) from within a context of a mini-protocol.

@erikd you're asking for a clean shutdown of the subscription worker (and server, as a similar story will come back from devops at some point) which we currently don't have.

@erikd please don't use `nullTracer`s, this will end-up in a state where we cannot debug application, especially deployed by a 3rd party. @CodiePP team has been working on limitting the output of logging and providing usful tracing switches.

**Comment by erikd** [comment]
@coot Why is it you think you are doing the right thing when you catch `StackOverflow` or `HeapOverflow` exceptions and just swallowing them instead of cleaning up and re-throwing them?

**Comment by avieth** [comment]
> @coot Why is it you think you are doing the right thing when you catch StackOverflow or HeapOverflow exceptions and just swallow them instead of cleaning up and re-throwing them?

These are async exceptions, no? Nobody is saying it's good to squelch async exceptions.

**Comment by erikd** [comment]
As for `nullTracer` they were added to the explorer by the network team when the explorer was updated to use the new network code. I would be fine with adding real tracers there, as long as logging is sensible and I can specify that only `logError` messages come out of the networking code, and everything from `logDebug` up to come out of the explorer code. @CodiePP is this possible?

**Comment by erikd** [comment]
@coot 
> I'd argue that the SomeException here is not a problem

@avieth :
> Nobody is saying it's good to squelch async exceptions.

**Comment by avieth** [comment]
^ Oh maybe he is saying that?

Come to think of it, in the context of a connection thread, maybe it _is_ ok to squelch asyncs? If something `throwTo`s the connection thread, or if the thread has a stack/heap overflow, anything it all, that thread dies, and the governing server thread does not _necessarily_ die. If the exception _really were_ fatal to the governing server thread then _it would be thrown there_, wouldn't it?

**Comment by erikd** [comment]
It is absolutely not ok, the catch and swallow whatever exception `error` and `exitFailure`/`exitSuccess` throw. By all means catch the exception, clean up and then rethrow, but just swallowing them and retrying is just wrong.

**Comment by avieth** [comment]
> By all means catch the exception, clean up and then rethrow, but just swallowing them and retrying is just wrong.

This is not at all clear. Also, to be precise, we're not "swallowing them and retrying", we're letting the connection thread die without killing the server. Nothing is retired.

**Comment by avieth** [comment]
> This is not at all clear.

On the one hand, you'd like your `panic`s to stop the executable. On the other hand, our users would like our servers to be available, even if some other request caused an error.  ¯\_(ツ)_/¯

**Comment by erikd** [comment]
How is my client progam supposed to notify the network that "the impossible happened, please print this message and then abort the whole program" ?

**Comment by avieth** [comment]
> How is my client progam supposed to notify the network that "the impossible happened, please print this message and then abort the whole program" ?

Maybe it's not supposed to? Why should it about the entire program? Is it not enough to kill the current request handler?

**Comment by erikd** [comment]
In the explorer, why would it continue running if it cannot connect to the database?

**Comment by avieth** [comment]
> In the explorer, why would it continue running if it cannot connect to the database?

Because the database may come back up later on.

**Comment by disassembler** [comment]
I think there needs to be a boundary between resiliency and catching everything. On the server side, building resilient systems that can auto-recover from failures is great (as long as it really can always auto-recover or quits if it really can't auto-recover). This also is typically easier to do as you know the states of your system and the transitions between them so you can identify exactly what failure modes are critical and which can be resiliently recovered.

On the client side though, third party developers (and internal ones developing client applications) should be able to tell their code to exitFailure and not expect the network library to not exit with a failure because it catches the exception. It's very important to have a subset of errors that you know you can safely recover from, catch those and do something (like restart a thread). But for the errors that truly crash the system and the system doesn't know how to recover should always exit hard so on-call engineers are alerted (or possibly the OS might have a restart failure policy that brings the service back up).

Under no circumstances should you ever catch an error and not rethrow it if you don't know exactly what transitions can get the system into that broken state.

**Comment by avieth** [comment]
> Under no circumstances should you ever catch an error and not rethrow it if you don't know exactly what transitions can get the system into that broken state.

Sounds right but honestly I don't think it works so well in practice. If I use some 3rd party library, I don't know which exceptions it might throw, but I do know that I don't want my server to crash just because one request triggered a failure in that library.

**Comment by avieth** [comment]
> third party developers (and internal ones developing client applications) should be able to tell their code to exitFailure and not expect the network library to not exit with a failure because it catches the exception

What we could do is build-in a mechanism by which a connection handler can indicate that the whole server should go down. Then the developer can use that when they know this is what they want. What's more, when running in production, we can instruct the server to ignore this indication.

**Comment by erikd** [comment]
Right, so can roll our own specialised version of functionality that already exists in the base library. Really?

> If I use some 3rd party library, I don't know which exceptions it might throw, 

Exceptions should never cross API boundaries. Yes the Haskell base library gets that wrong, but it is like that for historical reasons. We should not be making the same mistake.

**Comment by avieth** [comment]
> Right, so we can roll our own specialised version of functionality that already exists in the base library. Really?

Could you be more specific? I don't understand what you're trying to imply.

> Exceptions should never cross API boundaries.

Sure I agree. But that's not the state of real world.

>  It should not catch SomeException but a restricted subset. Eg, for an something like readFile catching anything more than IOException is un-necessary.

I think maybe we're straying too far from the point here. Let's keep it focused on what's actually going on: a server loop runs `IO`s per-connection and catches all sync exceptions, logging them but not re-throwing them. It does this so that one connection failing does not kill _every other connection_ thereby denying service to other users. Do you honestly believe that's a bad thing?

**Comment by erikd** [comment]
> Could you be more specific? I don't understand what you're trying to imply.

The base library provides `exitFailure` which in the explorer does not work because `network` catches and squelches the exception.

> Sure I agree. But that's not the state of real world.

My preferred solution is to catch exceptions at the boundaries between my code and the real world and turn them into `Left`s. Then across my packages exceptions never cross API boundaries. This works *really* well!

> a server loop runs IOs per-connection and catches all sync exceptions, logging them but not re-throwing them

Actually, it does not log them if the client code passes in a `nullTracer` so we end up with exceptions being silently caught and discarded. We should aim for APIs which cannot be used incorrectly.

**Comment by avieth** [comment]
> The base library provides exitFailure which in the explorer does not work because network catches and squelches the exception.

If a 3rd party library uses `exitFailure`, do we really want the server to go down?

> Actually, it does not log them if the client code passes in a nullTracer so we end up with exceptions being silently caught and discarded. We should aim for APIs which cannot be used incorrectly.

Do you consider giving a `nullTracer` to be incorrect use?

> My preferred solution is to catch exceptions at the boundaries between my code and the real world and turn them into Lefts. Then across my packages exceptions never cross API boundaries. This works really well!

I fail to see how this is any sort of solution to what we're discussing. You're talking about _your_ code, which of course _you_ can design in a nice way; but I'm wondering about 3rd party code, which _can_ and _often does_ throw exceptions all over. The goal here is to ensure that a failure in one connection does not kill all other connections. How do you propose to do that? If you use _any_ 3rd party code, you had better catch all exceptions.

**Comment by avieth** [comment]
Maybe what's at odds here is how we're thinking about what the program is and ought to do. The program that runs per-connection has, in my view, a different semantics for errors from the server program that spawns them. A failing client handler program does not imply a failing server. 

In general, a failing child thread really ought to propagate the failure/exception up to its parent. But our case of a server is different. We want it to be available. Errors should be reported, but should not bring it down unless it really _is_ a failure fatal to the entire server executable. And if that's the case, it'll go down anyway, regardless of whether we squelch client handler exceptions.

**Comment by erikd** [comment]
> If a 3rd party library uses exitFailure, do we really want the server to go down?

Absolutely, and we should either fix it or stop using that library. Same for libraries that use `error` for cases other than "the impossible happened and there is no way back to a sane state".

> Do you consider giving a nullTracer to be incorrect use?

I consider silent catching and swallowing exceptions to be at the very high end of of incorrect. If my code passes `nullTracer` into the `network` code all exceptions get silently caught and swallowed.

> You're talking about your code, which of course you can design in a nice way; 

Actually, I'm talking about IOHK's code. I think we should attempt to design IOHK"s code in a nice way.

> but I'm wondering about 3rd party code, which can and often does throw exceptions all over.

Yes, and I am suggesting that the solution is to catch exceptions at the interface between our code and third party libraries. 

This is not some academic preference. This was the way we designed our systems at my last employer and it worked incredibly well.

If I can't get you to stop catching `SomeException` can I pass in a list of exceptions that I do **not** want caught?

**Comment by avieth** [comment]
> Absolutely, and we should either fix it or stop using that library.

Not the answer I was expecting. Think of it this way: a server is parametric in the program it runs per-connection. Should that program be able to kill the whole server? If yes, it should be explicit, visible in the type, and should not be _overloaded_ as exceptions are. Letting an `exitFailure` or similar sync exceptions kill the server is begging for an accident.

> I consider silent catching and swallowing exceptions to be at the very high end of of incorrect. If my code passes nullTracer into the network code all exceptions get silently caught and swallowed.

This is orthogonal to silent catching and swallowing of exceptions. A tracer is for tracing, for catching/throwing/etc. You have the option to pass `nullTracer` if you don't care about tracing exceptions. That's your call, but it's certainly not incorrect. Sometimes we really don't care about tracing.

> Yes, and I am suggesting that the solution is to catch exceptions at the interface between our code and third party libraries.

But then we're catching `SomeException`, which you are strictly opposed to.

> If I can't get you to stop catching SomeException can I pass in a list of exceptions that I do not want caught?

I couldn't see that working. The server _must not go down_ because of some rogue sync exception. That's it that's all. It's a feature of the server. One failing client does not cause all other clients to fail.

**Comment by erikd** [comment]
Ouroboros-network is a *library* not and an executable.

The explorer *program* (lets call it layer 0) calls into `network` (layer 1) which calls back into code in the `explorer` (layer 2). Since `network` has chosen to catch `SomeException` (which is actually *all* exceptions) that means that is it impossible for explorer code in layer 2 to throw an exception to explorer code in layer 0. In other words the `network` library is imposing its idea of how the *program* should work on the *program*.

> But then we're catching SomeException, which you are strictly opposed to.

The `network` library is using exceptions for control flow (which has been considered an anti pattern for at least 20 years) and not just that, it is using the broadest, catch-all exception for control flow. If instead it was using its own internally defined exception for control flow it would be none of my business.

> The server must not go down because of some rogue sync exception 

Where do you propose that coming exception is coming from? `network` uses a very small set of upstream libraries. These libraries are well understood and I would be surprised if any of them threw any exception other than `IOException`. In fact its such a small set of libraries that auditing them for exception usage would be a couple of hours work at most.

**Comment by avieth** [comment]
> that means that is it impossible for explorer code in layer 2 to throw an exception to explorer code in layer 0

It's not. You can still `throwTo`.

> The network library is using exceptions for control flow (which has been considered an anti pattern for at least 20 years) and not just that, it is using the broadest, catch-all exception for control flow. If instead it was using its own internally defined exception for control flow it would be none of my business.

The case we're discussing now is not an example of exceptions for control flow. Catching exceptions in order to stop the program from crashing is not control flow. It could be that other parts of ouroboros-network do that, I don't know, but it's not relevant to this discussion.

> Where do you propose that exception is coming from? network uses a very small set of upstream libraries. These libraries are well understood and I would be surprised if any of them threw any exception other than IOException. In fact its such a small set of libraries that auditing them for exception usage would be a couple of hours work at most.

Do you volunteer?

Honestly, even if we had an audit, it doesn't change the fact that for a server, not crashing when a client thread crashes is a pretty important feature. Exceptions are still visible by way of a `Tracer` parameter. Yes, this is a library we're talking about, but the library provides an accept loop server that quite simply _should not crash_ if one of its threads crashes.

**Comment by erikd** [comment]
> You can still throwTo.

What if its the same thread?

> Do you volunteer?

Volunteer for auditing the libraries used by `network` for which exceptions they throw? Sure, I would do that if there was some chance of that information being acted on.

> Yes, this is a library we're talking about, but the library provides an accept loop server that quite simply should not crash if one of its threads crashes.

Firstly catching `SomeEcxeption` to meet that goal is like using a sledgehammer to crack a wallnut.

Secondly @disassembler , whose team will actually be running the most critical versions of this code disagrees:

> But for the errors that truly crash the system and the system doesn't know how to recover should always exit hard so on-call engineers are alerted (or possibly the OS might have a restart failure policy that brings the service back up).

**Comment by avieth** [comment]
> What if its the same thread?

Yes you can `throwTo` your own thread.

> > But for the errors that truly crash the system and the system doesn't know how to recover should always exit hard so on-call engineers are alerted (or possibly the OS might have a restart failure policy that brings the service back up).

Such as? NB: we're talking about errors that arise _within client connection handlers_. Are these ever truly fatal errors? Honestly I don't believe they ever are, nor ever should be. On the other hand, I could imagine a fatal error within the `ChainDB`, something which really cannot be recovered from. In that case, it _can_ kill the whole program, for the `ChainDB` is bracketed independently from a server! There's no problem here: the exception will ultimately kill the _server_ and therefore all of its client threads.

> Firstly catching SomeEcxeption to meet that goal is like using a sledgehammer to crack a wallnut.

No, it's the sensible thing to do. AFAICT there's frustration here because of a long and annoying debugging session that perhaps could have been made shorter if the server would crash when client threads crash. But as I keep repeating, that's not a good idea. But the trade-off really isn't as bad as it would seem from what I'm reading in this thread. If your program is to run in a server's client thread, its exceptions are not re-thrown. That's fine, for you can still observe those exceptions--you define the client program, after all. I think it's quite reasonable to expect different error semantics for your program, given that you are passing it to another program that is responsible for invoking it.

**Comment by coot** [comment]
@erikd we have two use cases here:
* a standalone node
* a client application using `ouroboros-network`

In the first case we have to be careful: in the past there were attacks which triggered a specialised exceptions which brought a whole server down. For cardano this can be fatal on a large scale: non recoverable halt of the whole system. Relaying on a review of all the dependencies, would also mean we need to repeat a careful analysis every time we update dependencies - that's a fragile process, and I prefer to design something solid instead.

The second case is different, and I see your points. Recently we merged error policies, and you will be able to catch and re-throw exceptions that you don't want to be caught, e.g. `AsyncExceptions` and alike. We also have a clean way of shutting down subscription worker (and server) which does not involve exceptions (by means of an `STM` transaction).  We haven't exposed it, but I think it will be useful for you. Whenever the [mainTx](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-network/src/Ouroboros/Network/Subscription/Ip.hs#L138) `retries` the subscription worker continues: we can expose a `TMVar ()` which allowed you to stop the worker (server has a similar api).

**Comment by avieth** [comment]
I just reviewed the discussion here and I think my point can be summarized by comparing to a shell. The server provided by ouroboros-network is like bash, and connection handlers for clients which it runs are like programs spawned by bash. Would it be nice if running `ls` could crash the entire shell? What if running `ls` reveals via syscall a bug inside the kernel, should it crash the shell? No, the *kernel* should panic instead. Exactly analogous to what we have here: if a client thread notices an internal error in some subsystem like the chain DB, it's not the thread's responsibility to tear things down, it's the responsibility of that essential subsystem to panic.

**Comment by coot** [comment]
@erikd since error policies are merged you actually can shutdown your client by `exitFailure`, you just need to configure `ErrorPolicies` so that `ExitCode` exception becomes fatal. Add
```
ErrorPolicy (\(_ :: ExitCode -> Just Throw)
```
to your error policies.  Tthe `ErrorPolicies` (note the prular) is a monoid so you can merge the `Ouroboros.Network.NodeToClient.networkErrorPolicies` with the policies of your application. If you do that `exitFailure` in one of your protocols will exit the app.

By design, and we'll speak with devops on this, you don't have a way to kill the node the client is connected to. If your client app has a problem accessing db, or some other fatal error happens to it, the node (which is a separate process) can happily run and sync / update its chain and the client can be restarted and it can connect to it.

If a node dies, the client will notice that the connections went down.  The subscription manager will kick in and it will connect to the node as soon as the node is up again.

I am closing this issue, as I feel this has been resolved with the error policies. You will still see `SomeException` in the code, but the threads will exit promptly and the behaviour is governed by error policy. We use sensible traces so these exceptions will be visible in the logs.
