### ISSUE TITLE
Record validation error in InvalidBlock error in chain sync client

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1254]

**Comment by nfrisby** [comment]
I just noticed this the other day as well. On my Issue 1202 branch, I'm now recording these via a `Tracer` and the ultimate `Property` is checking that it's empty (or only as-expected for tests that we expect to create invalid blocks -- eg due to stale delegation).

What do you mean by "record"? Apply a `tracer`? Raise an exception?

**Comment by mrBliss** [comment]
Addressed in #1279.
