### ISSUE TITLE
Mempool should cache "final ledger state"

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1301]
The mempool should store a reference to the ledger state after all transactions have been validated. Then when new transactions get added, and the ledger state at the tip of the chain has not changed, we can skip transaction evaluation altogether (`initVR`, `afterKnownValid`) and just reuse the previously stored ledger state. This could greatly improve the performance of the mempool, with relatively low memory overhead (I think).

**Comment by dcoutts** [comment]
Nice idea. Not critical yet. Lets wait 'til we have a good benchmark and/or profile of high throughput tx submission so we can measure the effect of the change (which should mostly be reduced CPU use for the case of a relay getting lots of txs from lots of peers at once so that it does not benefit from batching).

**Comment by dcoutts** [comment]
Apparently the latest benchmarks indicate that this is now a measurable effect, with the time to add a single tx being linearly related to the size of the mempool. This doesn't mean we have to prioritise this now.
