### ISSUE TITLE
Rewinding the PBFT ChainState to an EBB fails

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1312]
See https://github.com/input-output-hk/ouroboros-network/pull/1284#issuecomment-560976105

**Comment by nfrisby** [comment]
We discussed three options today.

  * Option A. Complicate the PBFT chain state and/or code to track EBBs.
  * Option B. Complicate the CS client to exclude EBBs from the intersection point candidates.
  * Option C. Relax the PBFT chain state code to assume that all `rewind: rollback to block not previously applied` errors are due to rewinding to an EBB, and so shouldn't be treated as errors. (What should happen in that case, rewind to the latest previously applied block prior to that EBB?)

Right now, as of PR 1284, `master` has a hybrid A/C, where it assumes a rewind to slot 0 can only fail with `rewind: rollback to block not previously applied` due to the epoch 0 EBB and so falls back to rewinding to `Origin`. This works because the test infrastructure only ever forges the epoch 0 EBB.

We're leaning towards option C but are hesitant since it could mask other bugs.

---

In production, "by the time our nodes take over, the EBBs will be much longer than K back" (-Duncan). So I had thought there was another option to just update the test infrastructure to only have "historical" EBBs, by starting the (first) nodes with a non-empty ImmDB. However, "Thomas is right of course that [...] we can lose data and roll back into the old region of the chain." (-Duncan). It took me a while to process that and realize that even if only one node truncates its ImmDb (eg disk failure), the resulting CS interactions may involve `MsgIntersectFound`s that target EBBs -- and those messages' handlers will incur failing calls to `rewind`.

**Comment by mrBliss** [comment]
> Option C. [..] (What should happen in that case, rewind to the latest previously applied block prior to that EBB?)

That's my first thought. Now I'm thinking about the following: say we have the following chain:

```
slots: 10    20          20 + k
.. ->  A  -> EBB  -> .. -> X
```
There is no block between A at slot 10 and the EBB at slot 20. If we now need to rewind `k` (our maximum rollback) slots from X to the EBB (because we found an intersection with the EBB), we should not return the `ChainState` of the latest previously applied block prior to that EBB, i.e. the `ChainState` for A, because that `ChainState` is older than `k` blocks.

Note that this scenario is very unlikely to happen in practice as there are nearly no empty slots (in the Byron-era that has EBBs).

**Comment by nfrisby** [comment]
> If we now need to rewind k (our maximum rollback) slots from X to the EBB (because we found an intersection with the EBB), we should not return the ChainState of the latest previously applied block prior to that EBB, i.e. the ChainState for A, because that ChainState is older than k blocks.

> Fortunately, I think that we'll do the right thing automatically if we recursively call rewind for the slot (of the block) before the EBB when finding out that there's only an EBB in that slot.

I agree with that assessment. If we have correctly implemented "rewind to the latest previously applied block prior to that EBB", then "rewind to 20" is effectively equivalent to "rewind to 10", and so both of those should fail. (This is what I want and think is happening on PR 1317.)
