### ISSUE TITLE
Please define a proper type for the return type of tx submission

### ISSUE THREAD

**Issue by erikd** [input-output-hk/ouroboros-network#1335]
It seems the type of `reject` in:
```
txSubmissionClient
  :: forall tx reject m. (MonadIO m, MonadSTM m)
  => StrictTMVar m tx
  -> LocalTxSubmissionClient tx reject m Void
```
is actually `Maybe String`. 

`String` is a really poor type for things like error messages  because pattern matches on them are fragile (because they can be changed without that change being reflected in the type). I would also advocate against having this return `Maybe` because `Maybe` is a little too generic.

I would suggest a proper sum type like this:
```
data TxSubmitStatus
  = TxSubmitSuccess      -- Tx sucessfully submitted
  | TxSumbitError1 a
  | TxSubmitError2 a b 
  ....
```
and the provide a render function with a type of:
```
renderTxSubmitStatus :: TxSubmitStatus -> Text
```
which renders the submission status values to `Text` for displaying to humans.

There should be at least one constructor for each different reason a tx submission can fail.

**Comment by mrBliss** [comment]
> It seems the type of `reject` in:
> 
> ```
> txSubmissionClient
>   :: forall tx reject m. (MonadIO m, MonadSTM m)
>   => StrictTMVar m tx
>   -> LocalTxSubmissionClient tx reject m Void
> ```
> 

Where do you see this in the code? Are you talking about the [`TxSubmissionClient`](https://github.com/input-output-hk/ouroboros-network/blob/a5827b1913a4892e25f6f53a92fd48a2a64f1191/ouroboros-network/src/Ouroboros/Network/TxSubmission/Outbound.hs#L108) or the [`LocalTxSubmissionClient`](https://github.com/input-output-hk/ouroboros-network/blob/a5827b1913a4892e25f6f53a92fd48a2a64f1191/ouroboros-network/src/Ouroboros/Network/Protocol/LocalTxSubmission/Examples.hs#L27)?

> is actually `Maybe String`.
> 
> `String` is a really poor type for things like error messages because pattern matches on them are fragile (because they can be changed without that change being reflected in the type). I would also advocate against having this return `Maybe` because `Maybe` is a little too generic.
> 
> [..]

As far as I know, that `reject` type variable will be instantiated with the right error type, not a `String`. IMO, we can't *nor should instantiate* it to the exact error message (without type parameters) here:
* The error message depends on which ledger is used and the network and consensus code is parametric in the protocol/ledger type(s). This is an important part of the design.
* This client lives in the networking library, which is agnostic of consensus and ledger related type. You can define a new client at a higher level, depending on both network and consensus, though.
* For testing purposes, it is easier to be parametric in its type.

You are often arguing for using as much concrete types as possible, because they make things simpler. This is true, but we should strike a balance. Being parametric has important advantages, like lower coupling/more modular/fewer assumptions, being easier to test, etc. If network clients need to be aware of which ledger is being used, we're going back in the direction of `cardano-sl` :wink:.

**Comment by erikd** [comment]
> Where do you see this in the code? 

The function I pass to  `....LocalTxSubmission.Client.localTxSubmissionClientPeer` is generic in `reject` but when I concretize it it become `Maybe String`.

> If network clients need to be aware of which ledger is being used, we're going back in the direction of cardano-sl.

Firstly, how many networks/blockchains are we supporting? I think its only one. So how about concrete first and then generalize it when we need it?

Second, surely we can have a single sum type all the errors for all the blockchains and networks we support?

**Comment by erikd** [comment]
After actually getting this working (and chasing a large number of incredibly verbose and rather unhelpful type errors) it turns out that the type I actually needed there (and I cannot understand why the `Maybe String` version was even exposed) it turned out to be `Maybe ApplyMempoolPayloadErr`.

This is still a poor type for what should be a **status**. For the vast majority of use cases of `Maybe a` the success result is `Just a` and `Nothing` represents failure. Your `Maybe ApplyMempoolPayloadErr` type flies directly in the face of this **convention**.

The type should be `ApplyMempoolPayloadStatus` and there should be no `Maybe` involved.

**Comment by mrBliss** [comment]
> Regardless of which Maybe String used the way it currently is, is close to the worst possible way to represent the result of a transaction submission.

> After actually getting this working (and chasing a large number of incredibly verbose and rather unhelpful type errors) it turns out that the type I actually needed there (and I cannot understand why the `Maybe String` version was even exposed) it turned out to be `Maybe ApplyMempoolPayloadErr`.

So you were complaining about `Maybe String` while it wasn't even `Maybe String` in the first place :grin: 

I'm still wondering where you saw that `String` :confused:

> This is still a poor type for what should be a **status**. For the vast majority of use cases of `Maybe a` the success result is `Just a` and `Nothing` represents failure. Your `Maybe ApplyMempoolPayloadErr` type flies directly in the face of this **convention**.
> 
> The type should be `ApplyMempoolPayloadStatus` and there should be no `Maybe` involved.

Complain to the people that designed the protocol. The protocol mentions a `reject` type parameter that is used when a transaction is rejected: https://github.com/input-output-hk/ouroboros-network/blob/c6c33a8289299fe5515b617dcb22d7266016e9f9/ouroboros-network/src/Ouroboros/Network/Protocol/LocalTxSubmission/Type.hs#L79.
