### ISSUE TITLE
Exhaustively list fatal exceptions in the error policy

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1553]
~There is no point listing all exceptions that should shut down the node; we have zero guarantees that this list is exhaustive, and so it is inevitable that some PR at some point is going to introduce an exception not in the list. The default should simply be that the node shuts down and is restarted.~

**EDIT:**
The default case in the error policy is *not* shutdown, but log + disconnect from peer.
> If a particular exception is not handled by any policy, a default kicks in, which currently means logging the exception and disconnecting from the peer (in both directions), but allowing an immediate reconnect. This is fine for exceptions that only affect that peer.

So the new goal of this ticket is to *exhaustively list fatal exceptions in the consensus error policy*.

**Comment by mrBliss** [comment]
The following comment in https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Node/ErrorPolicy.hs#L38-L43 actually states the opposite:

> If a particular exception is not handled by any policy, a default
> kicks in, which currently means logging the exception and disconnecting
> from the peer (in both directions), but allowing an immediate
> reconnect. This is fine for exceptions that only affect that peer.
> It is however essential that we handle exceptions here that /must/
> shut down the node (mainly storage layer errors).

@coot Is that comment correct? If so, would it make sense to make "shut down" the default?

**Comment by coot** [comment]
Yes that's correct, and the default was chosen because we don't want to accidentally shut down the node, e.g. one might mount an attack in which triggers error exception somewhere in the code.  If the default is to shut down, one could shutdown possibly a large portion of network.  We want to avoid this, that's why the default is to persist. 

@edsko if we miss a chance to shutdown because of an error what can go wrong? The node will keep running, maybe it will self corrupt its db.

Another note: all exceptions are logged (I hope with high severity - I will double check in `cardano-node`). So there is still information in the logs.  Maybe the ones that should kill the node, should be descriptive enough (or contain some keyword that could be parsed by tools).

**Comment by edsko** [comment]
@mrBliss so that means this ticket turns into "Let's make sure we really do exhaustively list all exceptions that should cause a DB revalidation" right?

**Comment by mrBliss** [comment]
> @mrBliss so that means this ticket turns into "Let's make sure we really do exhaustively list all exceptions that should cause a DB revalidation" right?

Indeed, I'll update the ticket

**Comment by edsko** [comment]
One exception that is missing:

```haskell
-- | Failed to strip off the envelope from an encoded header
--
-- This indicates either a bug or disk corruption.
data DropEncodedSizeException =
     DropEncodedSizeError CBOR.DeserialiseFailure
   | DropEncodedSizeTrailingBytes Lazy.ByteString
   deriving (Show)
```
