### ISSUE TITLE
Simplify encoder/decoder for PBftChainState

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1609]
since we anyway changed the binary format of the ledger state.

Assigning to this sprint. If we don't get it done this sprint, we should not do it at all, since it will require nodes to sync from scratch (or do it when we are forced to make another format change).

**Comment by mrBliss** [comment]
Since we store the `LedgerState` together with the `ChainState` on disk, and we're changing the former in a backwards incompatible way, we can remove our backwards compatibility code for the latter, including the golden tests for older versions. We should still keep a version number in the on-disk format of the `PBft` `ChainState`.

**Comment by nfrisby** [comment]
+1 for version number!
