### ISSUE TITLE
Duplicate block in vol DB?

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1638]
One of the Byron proxies was failing with

```
cardano-byron-proxy: UnexpectedError (ParserError (DuplicatedSlot (ByronHash{unByronHash = AbstractHash 194922fbdfd6060503a0cdce7b1d979a1802fa7b2c023fce59a83e54b982b254}) blocks-170.dat blocks-170.dat))
```

After https://github.com/input-output-hk/ouroboros-network/pull/1568 we will handle these errors and truncate the volatile DB when this happens, but it would still be good to know why it happened in the first place. Unfortunately, the fact that we will now just automatically truncate the volatile DB when we see a parse failure like this means that we're not very likely to see it in the wild. Reproducing it may be difficult.

**Comment by kderme** [comment]
The volatile db had a single file, which surprisingly had 18665 blocks. Two consecutive blocks (ordered 18627 and 18628) has same hash `194922fbdfd6060503a0cdce7b1d979a1802fa7b2c023fce59a83e54b982b254`.

**Comment by edsko** [comment]
> which surprisingly had 18665 blocks.

Why do you say this is surprising?

**Comment by kderme** [comment]
I think we have 1000 max blocks per file.

**Comment by kderme** [comment]
`ChainDB.cdbBlocksPerFile    = 1000`

**Comment by edsko** [comment]
But this is the proxy, which has

```haskell
  customiseArgs :: ChainDbArgs IO ByronBlock -> ChainDbArgs IO ByronBlock
  customiseArgs args = args
    { cdbBlocksPerFile = 21600 -- ?
    , cdbGcDelay = secondsToDiffTime 20
    }
```

(Don't ask me why :man_shrugging: :) )

**Comment by kderme** [comment]
I think this is related to how we don't close the db when there is an exception while modifying its state: `ExitCaseException _ex                 -> (mst, return ())`
Also possibly related, I count at least two threads which write blocks concurrently and it was mentioned that the process was going out of memory. According to these, a possible scenario is the following:

A thread tries to insert a block, manages to write the blocks to disk, but fails to update the in memory state due to an async exception. Before the exception kills the process, another thread tries to insert the same block, writes it again to disk and updates the in memory state. It manages to write a few other blocks before the process dies. Upon restarting the db is found corrupted.

Sounds possible?

I think, in any case, the internal state should be tagged as corrupted when we get an exception and we shouldn't just restore the previous state.

**Comment by mrBliss** [comment]
> I think this is related to how we don't close the db when there is an exception while modifying its state: `ExitCaseException _ex -> (mst, return ())`
> Also possibly related, I count at least two threads which write blocks concurrently ..

Can you show where in `cardano-byron-proxy` you see this?

> ... and it was mentioned that the process was going out of memory. According to these, a possible scenario is the following:
> 
> A thread tries to insert a block, manages to write the blocks to disk, but fails to update the in memory state due to an async exception. Before the exception kills the process, another thread tries to insert the same block, writes it again to disk and updates the in memory state. It manages to write a few other blocks before the process dies. Upon restarting the db is found corrupted.
> 
> Sounds possible?
> 
> I think, in any case, the internal state should be tagged as corrupted when we get an exception and we shouldn't just restore the previous state.

@edsko and I have discussed this a while ago but forgot to write down our conclusion. Your scenario sounds plausible. However, closing the VolatileDB when a thread writing to it gets terminated is not the right thing to do. Imagine a BlockFetchClient thread downloading blocks from another node. If we decide to disconnect from that node (e.g., the ChainSyncClient sees that its chain forked off too far in the past), we could terminate the BlockFetchClient thread while it is in the middle of adding the block to the VolatileDB. This should certainly not shut down the whole node. The node should keep on running and downloading blocks from other nodes.

So closing is not an option. Instead, **we should always write to the offset specified in the state** (`hPutAt`) instead of appending to the end of the handle (`hPut`). This way, the next write to the VolatileDB will simply overwrite the block instead of appending another one after it.

Also, with the improved validation of the VolatileDB (#1568), this is no longer a real problem, as the duplicated block would be truncated anyway.

@kderme Can you implement the above?

**Comment by kderme** [comment]
> > I think this is related to how we don't close the db when there is an exception while modifying its state: `ExitCaseException _ex -> (mst, return ())`
> > Also possibly related, I count at least two threads which write blocks concurrently ..
> 
> Can you show where in `cardano-byron-proxy` you see this?
> 

One is in `Ouroboros.Consensus.NodeKernel`
```
    -- Run the block fetch logic in the background. This will call
    -- 'addFetchedBlock' whenever a new block is downloaded.
    void $ forkLinkedThread registry $ blockFetchLogic

...

    addFetchedBlock :: Point blk -> blk -> m ()
    addFetchedBlock _pt = ChainDB.addBlock chainDB
```
And the other in `Byron` in the proxy itself:
```
  commitBlock :: CSL.HeaderHash -> CSL.Block -> IO CSL.HeaderHash
  commitBlock _ blk = do
    blk' <- recodeBlockOrFail epochSlots throwIO blk
    ChainDB.addBlock db blk'
    pure $ CSL.headerHash blk

```
> we could terminate the BlockFetchClient thread while it is in the middle of adding the block to the VolatileDB. This should certainly not shut down the whole node. The node should keep on running and downloading blocks from other nodes.

Maybe not shut down the whole node, simply close and reopen the volatile db, to trigger the validation.

>  **we should always write to the offset specified in the state** (`hPutAt`) instead of appending to the end of the handle (`hPut`). This way, the next write to the VolatileDB will simply overwrite the block instead of appending another one after it.
> @kderme Can you implement the above?

Yes, maybe I should also make it impossible to garbage collect the most current file, since this can also change the current write offset and cause further corruptions. I think we had considered doing this change for other reasons, too.

**Comment by mrBliss** [comment]
> > > I think this is related to how we don't close the db when there is an exception while modifying its state: `ExitCaseException _ex -> (mst, return ())`
> > > Also possibly related, I count at least two threads which write blocks concurrently ..
> > 
> > 
> > Can you show where in `cardano-byron-proxy` you see this?
> 
> One is in `Ouroboros.Consensus.NodeKernel` (commit [ac6ac3f](https://github.com/input-output-hk/ouroboros-network/commit/ac6ac3f302c800f397a59d91bbfb29477379f0c2))
> 
> ```
>     -- Run the block fetch logic in the background. This will call
>     -- 'addFetchedBlock' whenever a new block is downloaded.
>     void $ forkLinkedThread registry $ blockFetchLogic
> 
> ...
> 
>     addFetchedBlock :: Point blk -> blk -> m ()
>     addFetchedBlock _pt = ChainDB.addBlock chainDB
> ```

I think the proxy doesn't use that code path, as it doesn't use our BlockFetchClient (which is the sole user of `addFetchedBlock`), but downloads its block `cardano-sl`-style. I.e., the code you found below.

> And the other in `Byron` in the proxy itself (commit e363b00fc216e25240e055d38adfc794c100f1f2):
> 
> ```
>   commitBlock :: CSL.HeaderHash -> CSL.Block -> IO CSL.HeaderHash
>   commitBlock _ blk = do
>     blk' <- recodeBlockOrFail epochSlots throwIO blk
>     ChainDB.addBlock db blk'
>     pure $ CSL.headerHash blk
> ```

I have not checked this, but it might still be the case that the `cardano-sl` code downloads and adds blocks concurrently, though.


> > we could terminate the BlockFetchClient thread while it is in the middle of adding the block to the VolatileDB. This should certainly not shut down the whole node. The node should keep on running and downloading blocks from other nodes.
> 
> Ideally we would trigger the validation in this case, by closing and reopening the db, but I see how this may not be so easy to do.
> 
> > **we should always write to the offset specified in the state** (`hPutAt`) instead of appending to the end of the handle (`hPut`). This way, the next write to the VolatileDB will simply overwrite the block instead of appending another one after it.
> > @kderme Can you implement the above?
> 
> Yes, maybe I should also make it impossible to garbage collect the most current file, since this can also change the current write offset and cause further corruptions. I think we had considered doing this change for other reasons, too.

I think this is a good change, which will simplify things.

**Comment by mrBliss** [comment]
We can handle duplicate blocks thanks to #1568.
