### ISSUE TITLE
Implement permissive BFT

### ISSUE THREAD

**Issue by mdimjasevic** [input-output-hk/ouroboros-network#168]
Per discussion with @edsko, I'll implement an instance of the `Ouroboros.Consensus.Protocol.Abstract.OuroborosTag` class for the permissive BFT protocol.

**Comment by edsko** [comment]
Note that this depends on two improvements on the ledger side:

- Make the Block type polymorphic #304
- Split block header processing into protocol and payload components #305

**Comment by edsko** [comment]
Ok, so, change of plan. New plan is as follows:

* Ensure a clearer separation between "consensus stuff" and "ledger stuff" in the ledger spec (https://github.com/input-output-hk/cardano-chain/issues/305)
* Generalize the "consensus stuff" part so that it does not require a specific type of `Block` but is more polymorphic (https://github.com/input-output-hk/cardano-chain/issues/304). Note that there is no need to generalize the "consensus part", that can stay using a monomorphic `Block` type.

We would know we achieved our goal if we can run the Permissive BFT using the spec in our tests, using our `SimpleBlock` as the block type and our mock ledger (`Ouroboros.Consensus.Ledger.Mock`). 

This means that modifying the tests to use the "real" ledger can then properly be a separate task altogether (#243), and once done, we should then easily be able to run the real ledger with permissive BFT (#244), as well as other combinations.

**Comment by edsko** [comment]
Note on time estimate: allowing a fair amount of time here, since this is the first integration point and is therefore bound to require some massaging on both ends.

**Comment by mdimjasevic** [comment]
Now that there is _a_ protocol implementation for the permissive BFT, per @edsko the next step should be to get to a point where we can run the `test-consensus` test suite with PermBFT as the consensus algorithm.

**Comment by edsko** [comment]
Closing this as WONTFIX; we will only have the "real" implementation (#274).
