### ISSUE TITLE
Extend PBFT tests with software version update proposals/votes

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#1733]
Like Issue #1514 but for software updates instead of protocol parameter updates.

A proposal can include a protocol parameter update and/or a software update. The flow of a software update is a prefix of the flow of a protocol parameter update. Once a proposal is put forth, nodes can vote on it. Enough votes confirm it. Once that confirming vote is at least 2k slots old (ie "stable", based on the Byron chain density invariant), any software version update within the proposal has been adopted; nodes are expected to immediately restart in order to continue using new identified software version. This is how the nets' nodes will agree to hard-fork (which can  ultimately change anything, including in particular any protocol/node parameters not managed by parameter update proposals). Any protocol parameter update in the proposal is not yet adopted; see Issue #1514 for how that part separately continues.

This test need not actually update any software, but it should at least track that a net can extend a chain so that the tip of the starting chain and the tip extended chain induce two chain validation states that specify different adopted software version numbers.

Related: Issue #1514, Issue #1732.

**Comment by edsko** [comment]
If the discussion on Slack is correct, then this actually does not need to happen at all -- instead, the hard fork is triggered by a _protocol version_ update, and software version updates are basically totally irrelevant. But we should confirm that this is the case.

**Comment by edsko** [comment]
Giving this the same priority as #1514 for now, though we might end up closing this soon.

**Comment by edsko** [comment]
Conclusion here (@dcoutts , @dnadales , @nc6 ): please correct me if I'm wrong here, but: the publication of software versions onto the blockchain is actually irrelevant for the consensus layer proper (we never look at these versions). In addition, core nodes will probably not update themselves, and so for them too this is not so relevant. However, Daedalus _does_ look at this, and uses it to tell the user to update their wallet (and hence the underlying node), and we _will_ use this in the lead-up to the hard fork, because users must obviously have the latest version of the node installed before they can start running Shelley (a very similar story is true for Shelley-to-Goguen).

For this reason, leaving this at high priority. @nfrisby , @mrBliss and I think that testing this should be relatively easy: we must be able to submit and include transactions that update the software versions, and then we should check that the ledger state actually reports these new versions. Consensus itself will be entirely unaffected by this, and so there is no need for restarts or anything like that that would complicate the test infrastructure.

Can probably use the existing `GetUpdateInterfaceState` query for this.

**Comment by dcoutts** [comment]
> the publication of software versions onto the blockchain is actually irrelevant for the consensus layer proper (we never look at these versions)

That is correct.

> However, Daedalus does look at this, and uses it to tell the user to update their wallet (and hence the underlying node)

That is being discussed and may be changed. It's possible we'll remove on-chain notifications from Shelley entirely if Daedalus does not need them, because it is the only user of them. And Voltaire will change this all anyway (to be properly decentralised).

**Comment by mrBliss** [comment]
Removing high priority, as the wallet team has decided to no longer use this mechanism. 

> It's possible we'll remove on-chain notifications from Shelley entirely if Daedalus does not need them

@dcoutts confirms they will be removed.
