### ISSUE TITLE
Consensus tests: improve test data generation

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#1735]
Test data generation in the consensus tests currently is suboptimal:

* `TestConfig` contains `numSlots`, which should be derived in terms of `k`, but the generator for `TestConfig` has no access to `k`
* Ideally, `TestConfig` should also contain `EpochSize`, but that _must_ be derived in terms of `k` (at least for Byron), and so it's currently a separate parameter (https://github.com/input-output-hk/ouroboros-network/pull/1734)
* These are various uses of nested `forAll` (and worse, `forAllShrink`), that should be avoided to get reliable (or indeed correct) shrinking.

**Comment by edsko** [comment]
Marking as medium priority primarily because nested use of `forAllShrink` can lead to invalid test cases, which may send us down the wrong path entirely when debugging.

**Comment by edsko** [comment]
Note that this isn't quite as simple as adding a security parameter to `TestConfig`: many of the tests get some additional parameters (such as `PBftParams`) which themselves already imply a value for `k`.

**Comment by mrBliss** [comment]
@nfrisby Can we close this now?

**Comment by nfrisby** [comment]
> TestConfig contains numSlots, which should be derived in terms of k, but the generator for TestConfig has no access to k

That hasn't changed. But I think we're at least partially addressing the same fundamental concern by testing with small `k`. Currently every test (except for `RealTPraos`, which I'm trying to update now) uses `k <- choose (1, 10)` or `k <- choose (2, 10)` and a `numSlots <- choose (1, 100)`. So we explore various multiples of `k` number of slots, anywhere from `< 1k` up to `100k` (**not** uniformly distributed).

And sometimes the multiples of `k` cover multiple epochs. The tests with real ledgers get the epoch size from the ledger; so it's essentially fixed at `10k` since that's the baked-in value. For tests with mock ledgers, we either fix it to `10k` because "the ledger/protocol don't really care" (BFT, PBFT) or `choose (1, 10)` (LeaderSchedule, Praos, HFC).

This Issue can be closed if the above organization is acceptable. Work we could do: make the generators more directly/obviously cover multiple epochs, tune the distribution.

**Comment by edsko** [comment]
Yeah, seems fine to me.
