### ISSUE TITLE
Chain DB: avoid disk reads when moving a reader forward to the same point

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#1977]
Daedalus polls `GET /v2/network/information` every 2 seconds, causing `cardano-wallet` to send a `MsgFindIntersect [Origin]` request (see https://github.com/input-output-hk/cardano-wallet/blob/745aaad67004855a84c51e400c6fa1d10aedb910/lib/byron/src/Cardano/Wallet/Byron/Network.hs#L245) to the `ChainSyncServer` run by `cardano-node`. The `ChainSyncServer` uses a `ChainDB.Reader`, on which it calls `readerForward` with `[Origin]`.

Even though the reader is already at origin (a reader always starts at origin), this call to `readForward` with `[Origin]` causes it to open an ImmutableDB iterator starting from origin, costing us one (or two?) cached disk reads. These disk reads showed up here (see the small peaks):

![image](https://user-images.githubusercontent.com/373460/79761124-561b2380-8321-11ea-90fa-abb3c0ebc51f.png)

We can avoid these disk reads by not opening the ImmutableDB iterator when the reader is already at the given point.

**Comment by oneEdoubleD** [comment]
To test this on Windows, open Daedalus (Flight) and then using Process Explorer (procexp) look at the `cardano-node.exe` process spawned by `cardano-launcher.exe`. If this is happening you'll see `chain\immutable\00000.epoch` be opened and closed every two seconds and, in `properties/performance` you'll see recurring `I/O` values in `Read|Write|Other [Bytes] Delta`. If neither of these things can be observed then this issue is resolved.

**Comment by mrBliss** [comment]
@oneEdoubleD Now that #1978, which fixes this issue, has been propagated to `cardano-node`, could you double check that the disk reads are indeed gone?

**Comment by ArturWieczorek** [comment]
@mrBliss I was able to reproduce this issue first - then used newer version on node and don't see that problem anymore. Issue is fixed.

**Comment by mrBliss** [comment]
> @mrBliss I was able to reproduce this issue first - then used newer version of node and don't see that problem anymore. Issue is fixed.

Thanks for checking it :+1:
