### ISSUE TITLE
Update consensus tests to avoid assumption that we know the current slot

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#2027]
`WrappedClock` should go.

**Comment by edsko** [comment]
@nfrisby let's discuss this at some point.

**Comment by nfrisby** [comment]
Found #2047 while investigating this. Otherwise the primary culprit seems to be this hardcoded duration of `60s`.

https://github.com/input-output-hk/ouroboros-network/blob/776d76c24fb96ef4fb64f427f3989f1004ba2907/ouroboros-consensus/src/Ouroboros/Consensus/BlockchainTime/WallClock/HardFork.hs#L132

I'm working to integrate the test suite and that basic behavior. One option that doesn't require altering the existing property tests is to make this delay configurable and set it to the slot duration, though that might require oracular knowledge. I'm still working on this. I hesitate to alter the tests because the plan for testing proper Praos is likely to supplant any delicate balance struck here.
