### ISSUE TITLE
ChainDB: detect blocks from the future exceeding the clock skew not considered by chain selection

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#2232]
When a block B from the future is added to the ChainDB, the ChainDB will notice this in the following way. The block is part of a candidate selected by chain selection, after which it is validated.* If B is not invalid according to the ledger, the ledger state after the last (valid) block in the candidate is used to check whether the blocks in the candidate are from the future. At this point, we would mark blocks from the future exceeding the max clock skew as invalid.

(*) Note that we do chain selection before validation (to avoid validating candidates we wouldn't prefer) *and* after validation, because validation might truncate invalid blocks from candidates, which might make them no longer preferred over the current chain. 

If a block B from the future, exceeding the max clock skew arrives, but it is *not* connected to any other block or it doesn't appear in any candidate selected by chain selection, we won't *notice* it. It might be that after some time, long enough for B to no longer be from the future, a new block connecting B to the current chain arrives, at which point we adopt the B, *even though we should have considered it to be invalid*. If we had considered B earlier, we would have.

**Comment by edsko** [comment]
Having thought more about this, I now think that this is wrong. In principle, allowing for infinite clock skew should be fine (apart from storage considerations and potential DoS attacks); after all, we don't consider such blocks for chain selection, and so will only adopt them anyway by the time they become valid. 

Put another way: block validity should be determined by the block only; it doesn't make much sense to me to say, "this block is invalid because of the way you sent it to me".  If it's valid, it's valid.
