### ISSUE TITLE
Praos chainsync client timeouts

### ISSUE THREAD

**Issue by karknu** [input-output-hk/ouroboros-network#2245]
The chainsync client has a 70s limit when waiting for for a peer to announce a new block header. This causes a problem with Praos  since if the network doesn't produce a new block within 70s *every* node will disconnect from *every* other node. And they will all classify each other as misbehaving with a 200s timeout.

Instead of the 70s time limit a node should randomly pick a false positive target from an interval for every mux bearer.  The false positive target will be converted into a random time limit in seconds.

**Comment by MarcelKlammer** [comment]
![connection-drops-after-no-block](https://user-images.githubusercontent.com/2163046/84372119-f16e9d80-abda-11ea-99a7-283b91a5f8a3.png)

**Comment by karknu** [comment]
@MarcelKlammer Thanks, that looks very much like this bug.

**Comment by njd42** [comment]
Currently the ChainSync protocol sets a fixed timeout for a response for 'next tip please'. However, in Praos , the underlying determinism disappears. The time between blocks being minted is (basically) negative exponential distributed (not quite accurate for very small number of stakepools, handful or less, but practically indistinguishable for 20 and above).  Also, in Byron, this activity timeout was being used to ensure network connectivity (there is a separate mini-protocol for this purpose in Shelly).

Given that there is no fixed upper bound on inter-arrival interval whatever timeout we do set will (at some point in the future) be exceeded due to the 'expected' behaviour of the Praos leader selection. We knew that these timeout related issues would crop up and [analysis has been prepared.](https://docs.google.com/document/d/1DdpSLtFbdp3B6UjwFYZ2MOUoQ0YvDqiy3veKzOfYGaQ)

There is a secondary (system stability) issue - if all the nodes choose the same timeout then, when that interval actually occurs, all of them will be trying to find new peers at the same time. 

To avoid this 'storm' the following approach is recommended:
-  randomly choose a target 'false positive' threshold (Y) from a fixed set, say: 
   - 0.99; 0.999; 0.9999; 0.99999;  0.999999 and convert those into timeouts.
- conversion that target into a  timeout (see eqn below) - this would require access to $f$ and $T_s$ from the ledger state (updatable parameters, initial defaults from genesis).

 t = T_s [log (1-Y) / log (1-F)]

Note that non-functioning pools (as they are randomly chosen hence creating a Bernoulli sample from the original arrival pattern) remains a negative exponential distribution at a corresponding rate (ie reduces $f$ - each non-functioning pool reducing it by the ration of its stake to the total stake).
