### ISSUE TITLE
Remove supportedNodeToNodeVersions

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#2309]
Remove `supportedNodeToNodeVersions` and make `nodeToNOdeProtocolVersion` return a `Maybe`.

**Comment by mrBliss** [comment]
Summarising our discussion on Slack: the proposal was to change `supportedNodeToNodeVersions` to return *all* versions and that `nodeToNodeProtocolVersion` returns a `Maybe`: `Just` for supported and `Nothing` for unsupported versions so that we can get rid of [`error`s](https://github.com/input-output-hk/ouroboros-network/blob/4fa690a1fbd7fee5bca8d57e1df7ee2345146289/ouroboros-consensus-byron/src/Ouroboros/Consensus/Byron/Ledger/NetworkProtocolVersion.hs#L51) [like](https://github.com/input-output-hk/ouroboros-network/blob/9a7d0e06a7fad36c641e969a5a978b49178fdb0b/ouroboros-consensus-cardano/src/Ouroboros/Consensus/Cardano/Node.hs#L212) [these](https://github.com/input-output-hk/ouroboros-network/blob/9a7d0e06a7fad36c641e969a5a978b49178fdb0b/ouroboros-consensus-cardano/src/Ouroboros/Consensus/Cardano/Node.hs#L218).

I argued against both letting `supportedNodeToNodeVersions` return only the supported versions and letting `nodeToNodeProtocolVersion` return a `Maybe`. `nodeToNodeProtocolVersion` is only going to be called on versions in `supportedNodeToNodeVersions` anyway, so there would be *1.5 ways* of indicating support: include the version in the list *and* return `Just`, because including it but returning `Nothing` still means unsupported. This is no so clean and opens the door for inconsistencies.

However, for `CardanoBlock`, returning *all* versions including non-supported ones is annoying. We intentionally don't support all versions and have defined pattern synonyms for the versions we do support. Now we'd have to define the versions we intentionally *don't* support (also incompatible with the numbering scheme used internally), just to mention them in the list of *all* versions, only to return `Nothing` for them in `nodeToNodeProtocolVersion` :weary:.

Idea: what if we change
```haskell
supportedNodeToNodeVersions
    :: Proxy blk -> NonEmpty (BlockNodeToNodeVersion blk)
```
to
```haskell
supportedNodeToNodeVersions
    :: Proxy blk -> NonEmpty (NodeToNodeVersion, BlockNodeToNodeVersion blk)
```
and get rid of `nodeToNodeProtocolVersion`?

Alternatively:
```haskell
supportedNodeToNodeVersions
    :: Proxy blk -> Map NodeToNodeVersion (BlockNodeToNodeVersion blk)
```
This loses the non-emptiness, but it expresses that no two `BlockNodeToNodeVersion`s can map to the same `NodeToNodeVersion`. That can currently happen and we wouldn't realise it (`combineVersions` creates a `Map` with `NodeToNodeVersion`s as keys).


The same applies to `NodeToClient`.

**Comment by coot** [comment]
I like more the `Map` version. It's harder to make a mistake of using an empty map and also easier to diagnose, than having wrong `BlockNodeToNodeVersion blk` associated with a given `NodeToNodeVersion`.  At least from my point of view.

**Comment by mrBliss** [comment]
@coot What would we do here: https://github.com/input-output-hk/ouroboros-network/blob/557ef978ab4d69a02e25d646f8ce2530c8b5e2db/ouroboros-consensus/src/Ouroboros/Consensus/Network/NodeToNode.hs#L156? Would the handlers receive both `NodeToNodeVersion` and `BlockNodeToNodeVersion blk`?

**Comment by coot** [comment]
`NodeToNodeVersion` is necessary as it decides what network protocols are available; do we need to pass `BlockNodeToNodeVersion blk`? `blk` is usually available in some form in the handlers.

**Comment by mrBliss** [comment]
> `NodeToNodeVersion` is necessary as it decides what network protocols are available; do we need to pass `BlockNodeToNodeVersion blk`? `blk` is usually available in some form in the handlers.

The issue is that we start with `BlockNodeToNodeVersion blk` (defined in consensus) and pass that to the handlers, but some handlers, like the `BlockFetchClient`, are defined in network and don't know of `BlockNodeToNodeVersion blk`, so we currently convert them to `NodeToNodeVersion` using `nodeToNodeProtocolVersion`. But when that method is gone, we can't do that anymore. One solution is to pass both version types to the handlers (in `mkHandlers`) and then choose which of the two versions to pass to the implementation of the handler. We can then pass `BlockNodeToNodeVersion blk` to handlers defined in consensus and `NodeToNodeVersion` to handlers defined in network.

Alternatively, we create simple wrappers for all network-defined handlers in consensus that can take the a `BlockNodeToNodeVersion blk`. The nice thing about this is that it would complete the `Ouroboros.Consensus.MiniProtocol` hierarchy, which now lacks a few client/servers defined in network.

**Comment by coot** [comment]
Just passing `BlockNodeToNodeVersion blk` will not work, the network version is the source of truth about protocol version (e.g. usage of `MsgKThxBye`). It seems we need both.

@mrBliss we could try to move `BlockFetch` to `ouroboros-consensus`; I am not sure how well this will play with the `DeltaQ` changes @karknu is just working on.

**Comment by mrBliss** [comment]
> Just passing `BlockNodeToNodeVersion blk` will not work, the network version is the source of truth about protocol version (e.g. usage of `MsgKThxBye`). It seems we need both.
> 
> @mrBliss we could try to move `BlockFetch` to `ouroboros-consensus`; I am not sure how well this will play with the `DeltaQ` changes @karknu is just working on.

I wouldn't move `BlockFetch` entirely, just create a wrapper for it in consensus that can deal with this.

**Comment by mrBliss** [comment]
I realised the following in the shower:

The network needs a new version (`NodeToNode/ClientVersion`) when it introduces a new protocol, adds an extra protocol message, removes a protocol, etc. For example, adding the `LocalStateQuery` protocol required a new version for `NodeToClientVersion`. However, the serialisation format of consensus doesn't change with these versions. There is no point in introducing `ByronNodeToClientVersion2` just to enable the `LocalStateQuery` protocol, we just need to serialise more types, but we are not breaking compatibility of the existing serialisation format.

The network needs a new version because a protocol changes or is added/removed, *or* because the (consensus) serialisation format changes. The block-specific version number on the consensus side *only* needs to change in case of the latter.

The reason why the network version and the block-specific version map 1:1 is that we enumerate the block-specific versions and then map them to network versions. So every different network version needs a corresponding different block-specific version.

If we switch to the `Map NodeToNodeVersion (BlockNodeToNodeVersion blk)` approach as described in one of the comments above, we don't need the 1:1 mapping anymore. For example, enabling the `LocalStateQuery` protocol in V2 can be accomplished by:
```haskell
Map.fromList
  [ (NodeToClientV_1, ByronNodeToClientVersion1)
  , (NodeToClientV_2, ByronNodeToClientVersion1)
  ]
```

I was afraid that every network-side change that requires a new version (e.g., the upcoming keep-alive protocol) would require new versions numbers for each consensus block type, but that's not the case. Different network versions can simply map to the same block version :relieved:.

---

@edsko and I also discussed what it would mean to add an extra constructor to a consensus type: does that require a new version?

For example, when we add a new constructor `C` to the `Query` type of Shelley used in the `LocalStateQuery` `NodeToClient` protocol. Say we add a new version because of this change. An up-to-date client that has access to `C`, can try to submit a query `C` to a node. That node might or might not support `C`, but that will depend on the negotiated version. However, the client doesn't know that when it receives the user command to send query `C` to that node. What we *could* do, is throw a pure (!) exception in the encoder for the `Query` type in case of `C` in combination with an older version, terminating the connection. Alternatively, we send the `C` query anyway but now a receiving node that doesn't support `C` will fail decoding it and will terminate the connection. One could argue that the error message in the first case is clearer, but the end result is the same. So does it even make sense to introduce a new version when adding an extra constructor to a consensus type?

**Comment by coot** [comment]
> So does it even make sense to introduce a new version when adding an extra constructor to a consensus type?

I think this will be cleaner; we should also include such changes in `ChangeLog` file to communicate it.

**Comment by edsko** [comment]
Cleaner in which sense? Tooling can't take advantage of it, and the encoder would have to throw a pure exception. I'm not really sure that it's cleaner in any meaningful way.

**Comment by coot** [comment]
> Cleaner in which sense? Tooling can't take advantage of it, and the encoder would have to throw a pure exception. I'm not really sure that it's cleaner in any meaningful way.

Cleaner in the sense of versioning the software, not the code; I've seen external parties starting to build their own clients. It's probably enough if this is communicated with node version at this point.

**Comment by edsko** [comment]
> Cleaner in the sense of versioning the software, not the code; I've seen external parties starting to build their own clients. It's probably enough if this is communicated with node version at this point.

I see. As a form of documentation, you mean? That's fair enough, and we should indeed make sure that we communicate the differences between versions clearly.
