### ISSUE TITLE
Avoid need for `k` in `decodeByronChainDepState`

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#2383]
Right now this means `k` is part of the `CodecConfig`, which means client code needs to be aware of it. We could just store `k` alongside the rest of the state (at the cost of not being able to check that it's the right value).

We should probably do this as part of #2156 .

**Comment by dcoutts** [comment]
We currently have:
```-- | Node client support for each consensus protocol.
--
-- This is like 'Protocol' but for clients of the node, so with less onerous
-- requirements than to run a node.
--
data ProtocolClient blk p where
  --TODO: the mock protocols

  ProtocolClientRealPBFT
    :: EpochSlots
    -> SecurityParam
    -> ProtocolClient
         ByronBlock
         ProtocolRealPBFT

  ProtocolClientRealTPraos
    :: ProtocolClient
         (ShelleyBlock TPraosStandardCrypto)
         ProtocolRealTPraos

  ProtocolClientCardano
    :: EpochSlots
    -> SecurityParam
    -> ProtocolClient
         (CardanoBlock TPraosStandardCrypto)
         ProtocolCardano
```
It's a pain that clients of the node need to know these extra params simply to be able to talk to the node at all. It means they either need a config file, env vars or extra cli flags that nobody understands.

If we can eliminate EBBs in the client protocol the nwe don't need `EpochSlots` to be able to decode them, and if we can avoid `k` or otherwise separate the codecs needed for protocols vs those needed for disk, then we can eliminate the other param.

Finally, we can rename the constructors RealPBFT to Byron, TPraos -> Shelley.

**Comment by mrBliss** [comment]
Idea: introduce a separate `DiskConfig` to store these things. The end goal is to get rid of `CodecConfig` altogether.

**Comment by mrBliss** [comment]
> Idea: introduce a separate `DiskConfig` to store these things. The end goal is to get rid of `CodecConfig` altogether.

**Comment by mrBliss** [comment]
Oops, I just wanted to stop adding a new comment and thought "Close and comment" was "Cancel" (bad UX?).

**Comment by mrBliss** [comment]
> Idea: introduce a separate `DiskConfig` to store these things. The end goal is to get rid of `CodecConfig` altogether.

As #2510 shows, this does not solve the problem, as we sometimes need a `DiskConfig` when we only have access to a `CodecConfig`.

New plan: instead of changing the configs or including the `SecurityParam` in the encoding of `PBftState`, rethink the encoding of `PBftState`!

A while ago, pre-anchor signatures were added to the `PBftState` in #1307. IIRC, in that PR, @edsko was careful to maintain binary compatibility (to avoid a replay of the ledger from genesis). This meant that the decoder, which uses [`fromList`](https://github.com/input-output-hk/ouroboros-network/blob/d5fe0e587e36a08a54090e102e5ae51a31cd8f34/ouroboros-consensus/src/Ouroboros/Consensus/Protocol/PBFT/State.hs#L559) function, needed the `SecurityParam` and the `WindowSize` as arguments.

Since then, we have broken binary compatibility numerous times, even a few times to change the serialisation of `PBftState` itself (those cursed EBBs!).

Since we're now well in the Shelley era, breaking the compatibility of this format matters even less, as it's not stored on disk anymore.

Moreover, the serialisation is rather inefficient, it basically writes `(WithOrigin SlotNo, StrictSeq (PBftSigner c), MaybeEbbInfo)` to disk. This `StrictSeq` contains 2160 `PBftSigner`s, of which there are only 7 different ones. This means the same 7 `PBftVerKeyHash` (224 bytes each) are repeatedly encoded, instead of just once each. Something like `[(PBftVerKeyHash c, NonEmpty SlotNo)]` would be more efficient. This is no big deal (I know someone that doesn't care about these extra bytes :grin:) and we're not even writing this to disk anymore, it would be nice to fix this as well.
