### ISSUE TITLE
Implement singleEraTransition for Shelley

### ISSUE THREAD

**Issue by mrBliss** [input-output-hk/ouroboros-network#2471]
Related to #2452.

**Comment by mrBliss** [comment]
For documentation of this update process, see https://github.com/input-output-hk/ouroboros-network/pull/1741/

**Comment by edsko** [comment]
In order to avoid the same problem that we had with Byron (#2455), we could take the following approach:

* Blocks that came in within an epoch after the `4k/f` voting deadline are not relevant.
* Since there are gaps between blocks, we are probably only sure that there will be no more relevant block when we have seen the first block after the deadline.
* If we _count_ how many blocks we have seen post deadline, and we have reached `k` of them, we know that that last pre-* deadline block won't be rolled back anymore.
* At this point we can look at the ledger state and see which proposals we accepted in the voting period, if any, and notify the HFC is one of them indicates a transition.
