### ISSUE TITLE
Off-by-one error in TPraos history

### ISSUE THREAD

**Issue by nc6** [input-output-hk/ouroboros-network#2506]
As reported by @nfrisby :+1: 
First:
The anchor is the earliest slot to which we can roll back. It should correspond to the first slot with an entry in the historical state.
https://github.com/input-output-hk/ouroboros-network/blob/62e57b9673e0140c87c6edd6ca8fb7b813c9f8d9/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Protocol/State.hs#L45-L57
Second: the sequence of historical states -- which includes the current state -- never has more than k entries.
https://github.com/input-output-hk/ouroboros-network/blob/62e57b9673e0140c87c6edd6ca8fb7b813c9f8d9/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Protocol.hs#L403-L407
So we can only roll back to the first entry, which would involve dropping at most k-1 blocks.
Is my reasoning here sound?
If so, that is off-by-one with respect to the semantics of k:
k == 1: we can roll back at most one block
https://github.com/input-output-hk/ouroboros-network/blob/62e57b9673e0140c87c6edd6ca8fb7b813c9f8d9/ouroboros-consensus/src/Ouroboros/Consensus/Config/SecurityParam.hs#L15-L24
This is in some sense a minor discrepancy, considering k=2160 in production. But still, is it intentional/recorded anywhere?
Edit: Maybe a fix is as simple as instead pruning to a length of k+1, since the sequence includes the current state, IIUC.

**Comment by mrBliss** [comment]
I was mistaken, #2546 does not fix this issue. I got confused because `TPraosState` also keeps snapshots, but that's the `ChainDepState` of Shelley, not the `LedgerState` of Shelley.

I will fix it now, by maintaining removing the ability to rewind a `ChainDepState` and keeping the snapshots in the `HeaderState` instead of having to reimplement the snapshots for each ledger (Byron as well).

Note that the `HeaderState` will still contain snapshots, while we keep the last `k` `HeaderState`s around as part of the LedgerDB, so that's again snapshots within snapshots. I have some ideas on how to get rid of this too, but it's less straightforward than with the `LedgerState`, because we also use the `HeaderState` in the ChainSyncClient, where the `HeaderState` can be more than `k` blocks ahead of any `HeaderState` in the LedgerDB, but we might still need to roll it back `k` blocks when the upstream peer does so.

My plan is to store `HeaderState`s without snapshots in the LedgerDB and use the LedgerDB's snapshots to create a range of `k` `HeaderState`s, which can then be used as the starting point for the ChainSyncClient.

**Comment by nfrisby** [comment]
^^^ Issue 2574 identified this ticket as the cause of a failure during the recent nightly run.
