### ISSUE TITLE
Do not use withTimeoutSerial at the top level

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#3267]
`withTimeoutSerial` has a constraint (on Windows), that timeouts can only be
used serialy, i.e. within a single thread.  We cannot use it at the top level
and then passed to various threads.

There is also problem with peer state actions which are run asynchronously by
the p2p governor (e.g. the `closePeerConnection` is executed by
`jobDemoteEstablishedPeer` in a new thread).  We either need to lift the serial
constraint (not easy) or sprinkle some of the `PeerStateActions` with `withTimeoutSerial`.

This worked so far, as we mostly use it on `*nix` systems, the serial
constraint of `withTimeoutSerial` is only on `Windows`.

**Comment by karknu** [comment]
I think that this should be fixed by switching from `withTimeoutSerial` to `withTimeoutSerialNative` in `Diffusion/P2P.hs` . `withTimeoutSerial` is an optimization to be able to deal with per packet timeouts. The governor operates at a glacial pace, and therefor it doesn't matter if windows creates an extra thread to deal with its timeouts.

**Comment by coot** [comment]
This was fixed in the `p2p-master` branch (pr #3377).
