### ISSUE TITLE
Refactor prop_public_resolvessDomainsCorrectly

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#3415]
Refactor the `prop_public_resolvesDomainCorrectly` so that it just runs
a single simulation which resolves untill we get the expeted result, instead of
a recursive loop which at each step runs `IOSim`.

**Comment by bolt12** [comment]
Gave a go at this. There's no straightforward way to do this since it returns a set of `SockAddr`, I lose the information about the domain. That's why the test needs to run `IOSim` in order to look at the traces and build back the result domain map. One way to fix this would be to change the type signature to return the successful domain - ip pairs that were resolved.

**Comment by bolt12** [comment]
Managed to do it 😄
