### ISSUE TITLE
outbound-governor assertion failure: prop_governor_nofail

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#3494]
[CI failure](https://github.com/input-output-hk/ouroboros-network/runs/4236952362?check_suite_focus=true#step:28:577):
```
   Ouroboros.Network.PeerSelection
    basic
      has output:                                                     OK
        +++ OK, passed 100 tests.
      no failure:                                                     FAIL (79.57s)
        *** Failed! (after 99 tests and 91 shrinks):
        Exception:
          Assertion failed
          CallStack (from HasCallStack):
            assert, called at src/Ouroboros/Network/PeerSelection/Governor/Types.hs:399:5 in ouroboros-network-0.1.0.0-inplace:Ouroboros.Network.PeerSelection.Governor.Types
        GovernorMockEnvironment {peerGraph = PeerGraph [(PeerAddr 64,[],GovernorScripts {gossipScript = Script (Nothing :| []), connectionScript = Script ((ToCold,NoDelay) :| [(Noop,NoDelay)])})], localRootPeers = fromGroups [(1,fromList [(PeerAddr 64,DoAdvertisePeer)])], publicRootPeers = fromList [], targets = Script ((PeerSelectionTargets {targetNumberOfRootPeers = 0, targetNumberOfKnownPeers = 0, targetNumberOfEstablishedPeers = 0, targetNumberOfActivePeers = 0},NoDelay) :| [(PeerSelectionTargets {targetNumberOfRootPeers = 0, targetNumberOfKnownPeers = 1, targetNumberOfEstablishedPeers = 0, targetNumberOfActivePeers = 0},ShortDelay),(PeerSelectionTargets {targetNumberOfRootPeers = 0, targetNumberOfKnownPeers = 1, targetNumberOfEstablishedPeers = 0, targetNumberOfActivePeers = 0},ShortDelay),(PeerSelectionTargets {targetNumberOfRootPeers = 0, targetNumberOfKnownPeers = 0, targetNumberOfEstablishedPeers = 0, targetNumberOfActivePeers = 0},NoDelay),(PeerSelectionTargets {targetNumberOfRootPeers = 0, targetNumberOfKnownPeers = 0, targetNumberOfEstablishedPeers = 0, targetNumberOfActivePeers = 0},NoDelay),(PeerSelectionTargets {targetNumberOfRootPeers = 0, targetNumberOfKnownPeers = 1, targetNumberOfEstablishedPeers = 0, targetNumberOfActivePeers = 0},NoDelay)]), pickKnownPeersForGossip = Script (PickFirst :| []), pickColdPeersToPromote = Script (PickFirst :| []), pickWarmPeersToPromote = Script (PickFirst :| []), pickHotPeersToDemote = Script (PickFirst :| []), pickWarmPeersToDemote = Script (PickFirst :| []), pickColdPeersToForget = Script (PickFirst :| [])}
        Use --quickcheck-replay=255166 to reproduce.
```

**Comment by bolt12** [comment]
I investigated this issue and reached the conclusion that the error is due to race conditions on the `Governor`'s job pool. The high level idea of the problem is that the `Governor` makes some decisions (demote, promote to warm, promote to hot, forget peers) based on the current state and targets. When these decisions are made the Governor submits jobs to the pool to be run. But the state can be so volatile that before the job runs a bunch of other jobs are submitted as well and these can race with each other leading to invalid states.

In the particular case I am evaluating what happens is:

1. We get `Peer10` from LocalRoots
2. We ask to promote `Peer10` to Warm (job submitted)
3. Job (submitted in 1) to promote `Peer10` to warm finishes successfully
4. We ask to promote `Peer10` to Hot (job submitted)
5. Targets change to 0 and `Peer10` gets demoted
6. We ask to forget `Peer10` (no job submitted, this is done instantaneous, `Peer10` removed from `KnownPeers`)
7. Targets change to 1
8. We get peers from LocalRoots (`Peer10` back to `KnownPeers`)
9. We ask to promote `Peer10` to Warm (job submitted)
10. Job (submitted in 4) to promote `Peer10` to Hot fails (This removes Peer10 from `availableToConnect` set)
11. Job (submitted in 9) to promote `Peer10` to Warm succeeds (This breaks the invariant that `establishedPeersSet 'isSubsetOf' availableToConnect`)

There are probably other instances of this concurrency problem as pointed in issues: #3504, #3515, #3542, #3550 .

Note that this concurrency issue is only caused by our internals and can not be trigger from the outside.

Since the problem is concurrency one question to ask is why have a job pool in the first place where most of the jobs are not `IO` bound. And the answer to that is that the `Governor` will be managing possibly many connections and those ought to be independent hence having one thread per job. Another thought was to change to a job pool where, for each peer connection we would have a job queue making so that for a given peer we didn't make it possible to have race conditions between jobs. However, this last suggestion wouldn't work because the jobs do not have any notion of the current `Governor`'s state and if the state is volatile enough it can still lead to the same problems that were presented above.

Probably the most straightforward way to fix this problem is to somehow make the jobs aware of the current state and not run/fail if that would mean putting the state in an inconsistent state.

Our event waiting looks like this:
```haskell
    guardedDecisions :: Time
                     -> PeerSelectionState peeraddr peerconn
                     -> Guarded (STM m) (TimedDecision m peeraddr peerconn)
    guardedDecisions blockedAt st =
      -- All the alternative non-blocking internal decisions.
         RootPeers.belowTarget        actions blockedAt  st
      <> KnownPeers.belowTarget       actions     policy st
      <> KnownPeers.aboveTarget                   policy st
      <> EstablishedPeers.belowTarget actions     policy st
      <> EstablishedPeers.aboveTarget actions     policy st
      <> ActivePeers.belowTarget      actions     policy st
      <> ActivePeers.aboveTarget      actions     policy st

      -- All the alternative potentially-blocking decisions.
      <> Monitor.targetPeers          actions st
      <> Monitor.localRoots           actions st
      <> Monitor.jobs                 jobPool st
      <> Monitor.connections          actions st
```

That `Monitor.jobs jobPool st` waits for the first completed job in the `jobPool` . Each time that `guardedDecisions` returns the state `st` can change and due to the way it is implemented a lot of the non-blocking internal decisions can run before we get the first completed job (it won't starve but I don't think there are theoretical limits), hence the volatility of the state. If I put `job1` at state `st1`, it can happen that I will wait on `job1` with state `st10` (where `st10` can end in a possibly broken state if `job1` runs). We either program the job to accommodate this fact or need to make sure that `job1` will be waited with `st1` no matter what.

**Comment by coot** [comment]
I noticed that this is fixed by reordering `guardedDecisions` to:
```
      -- All the alternative potentially-blocking decisions.
         Monitor.connections          actions st
      <> Monitor.jobs                 jobPool st
      <> Monitor.targetPeers          actions st
      <> Monitor.localRoots           actions st

      -- All the alternative non-blocking internal decisions.
      <> RootPeers.belowTarget        actions blockedAt  st
      <> KnownPeers.belowTarget       actions     policy st
      <> KnownPeers.aboveTarget                   policy st
      <> EstablishedPeers.belowTarget actions     policy st
      <> EstablishedPeers.aboveTarget actions     policy st
      <> ActivePeers.belowTarget      actions     policy st
      <> ActivePeers.aboveTarget      actions     policy st

```
This puts all the monitoring tasks first and puts `Monitor.connections` before `Monitor.jobs`.

**Comment by bolt12** [comment]
Interesting, I see how it can appear to be fixed but I am worried if other issues can arise due to this ordering. I think there are other issues related to this loop, we can check if this reordering fixes those as well!
