### ISSUE TITLE
Identify possible untested parts of the code inspecting the UTxO-HD diff

### ISSUE THREAD

**Issue by Jasagredo** [input-output-hk/ouroboros-network#3944]
By inspecting the [UTxO-HD diff](https://github.com/input-output-hk/ouroboros-network/pull/3863) we can identify some other code chunks which are probably not being tested currently and might deserve some attention.

In particular, in a preliminary thinking, it seems that at least the following will probably not be already tested:
- Era transitions // HFC translations

**Comment by Jasagredo** [comment]
The things that might not yet be tested and that I have identified by looking at the diff are the following:

- ThreadNet tests: They are still disabled, we should attack this...
- Era transitions / HFC translations
- Cardano transitions
- Golden transition for Byron-Shelley and Shelley-Allegra on mainnet? These two are particular in the sense that Byron-Shelley populates the whole UTxO-HD tables and Shelley-Allegra have to adjust the AVVMs.
- Queries: some are tested by upper layers (tests in the node and wallet) but is that enough?

**Comment by bartfrenk** [comment]
I think it is wise to track those somewhere outside of this issue, so we can close this one. Pointwise:

1. Reactivating the ThreadNet tests is https://github.com/orgs/input-output-hk/projects/49/views/13.
2. There is something about transitions here: https://github.com/orgs/input-output-hk/projects/49/views/13 that already includes a strategy for testing transitions (namely using the ThreadNet tests).
3. Like above? Not sure what a Cardano transition is.
4. That seems sensible, but it also seems big. My understanding is too limited.
5. From a generic standpoint, I think it is a good idea to have these tests in consensus, since it seems a bit strange to rely on external clients not under our control (or partially under our control) to rely on testing exposed functionality. This https://github.com/input-output-hk/ouroboros-network/issues/3954 also seems to cover part of the concerns we had related to testing range reads through testing the queries.

**Comment by dnadales** [comment]
>  But maybe this becomes more of a techdebt issue as there are so many queries which are just untested even without UTxO-HD.

Indeed.

**Comment by dnadales** [comment]
The additional tests identified during this analysis were written down here https://github.com/input-output-hk/ouroboros-network/issues/4045
