### ISSUE TITLE
Peer Sharing - how is the reply to a share request calculated

### ISSUE THREAD

**Issue by njd42** [input-output-hk/ouroboros-network#3958]
* Do we need to make multiple / repeat requests idempotent? 
* What 'entropy' should be present in the responses?
* Should we share those known to be ledger peers at all? 
  * note that we can't take an IP address and determine if it is a ledger [reverse lookups just don't work]
  * not sharing our ledger peers could help with DDoS resistance

**Comment by bolt12** [comment]
After a node receives a Gossip request from another peer, before responding there are some things it needs to consider:

- Have I replied to this peer recently? If yes, then probably we should ignore the request, this way we do not keep information about the previous reply (avoiding having to keep more information than we have to) and it makes it clear a node does not benefit a lot from asking the same peer twice.
- Another check might be worth doing is that if we have any information about the willingness of this peer to participate in Gossip. However, a node might have reloaded its configuration with a new global configuration flag, enabling gossip participation. There's no way the request receiving node can know about this.. so maybe it does not make much sense to make this check.
- Should we rate limit gossip requests? Not sure this is an issue if we ignore requests from the same peer and have well configured targets.

After considering these items, the node needs to calculate its response. There's 2 ways one can probably go about this: The requesting end requests an upper-bound on the amount of peers to fetch or the replying end decides how many peers to give. I think the better way is for the requesting end to ask an upper-limit, since the other way around the receiving end would have to prune the requests anyway to avoid for huge dumps of information and possible resource usage exploits. Given this, a possible algorithm for computing the response can be:

- Compute a random number between 0 and the upper-limit;
- Take as many as the generated random number from the gossip-about set, according to some policy.

The gossip-about set should not include known-to-be-ledger peers and peers that have expressed their unwillingness to participate in Gossip, either via configuration file, wither by handshake.

The policy should also manage the amount of "entropy" in the response (e.g. pick a random percentage of cold/warm; maybe even some fake peers).

---

Questions: Should we gossip about Established peers? Or any Known Peers is enough? How can we introduce more entropy in our response?

**Comment by bolt12** [comment]
> What if a node restarts and we don't have cache of known peers implemented? If that information does not persist over lifetime of a connection, then we won't have any problems.

Not sure I understand what you're trying to say here. Are you saying what I said is okay even if we restart the node without any caching?

**Comment by bolt12** [comment]
> What if a node restarts and we don't have cache of known peers implemented? If that information does not persist over lifetime of a connection, then we won't have any problems.

Not sure I understand what you're trying to say here. Are you saying what I said is okay even if we restart the node without any caching?

> Isn't a random choice from our non-ledger gossipable known peers enough?

Yes but see above
