### ISSUE TITLE
Write a blog article about a consensus map

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/ouroboros-network#4145]
Re-organize the consensus docs, to improve their discoverability and announce this via a blogpost

The consensus map could be used for:
- Onboarding new collaborators.
- Identifying potential points of improvement.
- Hiring.
- Helping current collaborators.

One important message we want to get across is the fact that consensus:
- requires time to learn,
- it is mission-critical,
- it is highly rewarding to work on it, but it will take time till one can make a significant contribution.
 
## TODOs

* [x] #4149
* [x] #4057 
* [x] #4217
* [x] #4061
* [x] #4198
* [x] #4247
* [x] #4323
* [x] #4245
* [x] #4324
    * [x] Link to the Galois examples from the docs.
* [ ] ~Announce the new documentation somewhere (eg `cardano-updates` or engineering blog).~

## Tasks for later

* [ ] #4215
* [ ] #4153

**Comment by abailly-iohk** [comment]
Also: 
* The process will be documented along the way so that it can scrutinized by all team members, criticised and improved, something similar to [Hydra's](https://github.com/input-output-hk/hydra-poc/wiki/Logbook) or [Mithril's](https://github.com/input-output-hk/mithril/wiki/Logbook) logbooks,
* This will be time-bound, and will be released before Christmas (2022).

**Comment by abailly-iohk** [comment]
I have created a Miro board to support our work sessions: https://miro.com/app/board/uXjVPD75P0Y=/?share_link_id=947519689885

**Comment by dnadales** [comment]
Dependencies as of 15 Nov 2022.

![project-modules-deps-Mon Nov 14 17:00:27 2022](https://user-images.githubusercontent.com/175315/201911346-25128eb2-16c7-4197-9b7d-a25ea326f176.svg)

**Comment by nfrisby** [comment]
> before Christmas 2022

I consider that fast/short notice. When you say "blog post"---do you mean necessarily on the IOG public blog? I personally don't think we should rush anything out on official channels like that.

-----

I very much think this overview will be a great help. We should merge the Galois tutorial first so that this blog post can link to it as one of the "for more information see" options.

**Comment by dnadales** [comment]
@abailly-iohk I'm thinking maybe the scope and goal of this issue should simply be:

> re-organize the consensus docs, to improve their discoverability and announce this via a blogpost

And list the concrete issues we identified and which will support said goal:

- Add a consensus section to cardano-docs or developers.cardano.org
- Split Onboarding.md into CONTRIBUTING and README and organize info (https://github.com/input-output-hk/ouroboros-network/issues/4061)
- Redraw the diagram from network design doc linking to code and put in haddock (how? where?)
- Link to the Galois examples from the docs (see https://github.com/input-output-hk/ouroboros-network/pull/4186)
- Place docs/Testing.md closer to the code: 
    - Index them in the top-level haddock
    - Maybe the "leaves" should be inside the module.
- Index `ouroboros-consensus/docs`: we need to provide an overview of what's there.
- Define a strategy (agreed with the team) to gradually improve the consensus documentation.
- <plus the issues that are already in this ticket>

I'd be inclined to change this issue description to something like the contents of this comment. What do you think?

**Comment by dnadales** [comment]
The stubbed blog post can be found [here](https://github.com/input-output-hk/cardano-updates/pull/64).

**Comment by abailly-iohk** [comment]
Perfect!
