### ISSUE TITLE
Leverage existing mempool tests to make sure the new ledger interface is exercised properly

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/ouroboros-network#4172]
In https://github.com/input-output-hk/ouroboros-network/pull/4162 we simplified the ledger interface used by the mempool. This could enable us to leverage existing mempool tests to make sure the uses of the new ledger interface are exercised properly.  We should investigate if the existing mempool tests could already test different code paths in the mempool that are exercised depending on the answers that:

- getCurrentLedger
- getLedgerTablesAtFor

return.

As a first step, it might make sense to investigate if and how the baseline tests exercise this aspect.

**Comment by Jasagredo** [comment]
From what I can see on the existing Mempool tests I can draw the following information:

- There are pure TxSeq tests but we are not currently interested in these
- There are a number of different setups: `TestSetup`, `TestSetupWithTxs` `TestSetupWithTxsInMempool`
- The tests are based on running `IOSim` actions on a `SimpleBftBlock SimpleMockCrypto BftMockCrypto` system
- All the tests are sequentially executed
- The mock block holds a `Utxo = Map TxIn TxOut`. Could this be leveraged to use Ledger Tables? In particular could we use the current setup for generating data and then before returning the TestSetup use `unstowLedgerTables` or some such to move everything to ledger tables?
- As there are no blocks from the point of view of the mempool, it treats single transactions as full blocks and just increment the slot and rehash it (see `applyTxToLedger`)
- After each test, check that the contents of the mempool are valid plus the property being tested (see end of `setupAndRun`)
- `prop_Mempool_idx_consistency` tests that ticket numbers are not reassigned in a sequential scenario.

Next steps/questions:

- Do we want to test more in the sequential case? We don't do long sequences of actions but we do all actions repeated times in different properties. I mean that we don't `[add, remove, sync, add, sync,...]` but we check that `add` works as expected, `remove` works as expected, `sync` works as expected. Doesn't this mean that the general case is proven? 
- Is there a way to adapt this to the parallel case? In particular I'm thinking that instead of going through the whole boilerplate of QSM, it might be reasonable to do it in the same way the idx_consistency property works. I think maybe we can just generate pairs of commands and test them in parallel? Like `concurrently (\txsToAdd -> ...) (\txsToRemove -> ...)` and check the result. If all pairs work properly does this mean the general case also works as expected? We would have to run the test case several times the same way QSM does to ensure randomness in the RTS scheduling, but sounds doable.
- The generators take as base ledger `testInitLedger` but it could be adapted to take an already generated ledger so that we can build chains of setups which can translate in chains of actions. I think this is very doable and it can be used also on the parallel case.

This also opened a question. Should we modify the mock ledger to be able to work with tables? Probably not, the mock ledger should remain ignorant as the ledger does, but now the ledger state is simply the mockstate. It perhaps should have a distinction like the ShelleyLedgerState and then support stow and unstow "easily" 

Now:

```haskell
instance (SimpleCrypto c, Typeable ext) => TableStuff (LedgerState (SimpleBlock c ext)) where
  data LedgerTables (LedgerState (SimpleBlock c ext)) mk = NoMockTables
  ...


newtype instance LedgerState (SimpleBlock c ext) mk = SimpleLedgerState {
      simpleLedgerState :: MockState (SimpleBlock c ext)
    }
```

```haskell
import Ouroboros.Consensus.Mock.Ledger.UTxO (TxIn, TxOut)

instance (SimpleCrypto c, Typeable ext) => TableStuff (LedgerState (SimpleBlock c ext)) where
  newtype LedgerTables (LedgerState (SimpleBlock c ext)) mk = SimpleLedgerTables {
       getSimpleLedgerTables :: mk TxIn TxOut
  }
  ...


data instance LedgerState (SimpleBlock c ext) mk = SimpleLedgerState {
      simpleLedgerState :: MockState (SimpleBlock c ext)
    , simpleLedgerTables :: LedgerTables (LedgerState (SimpleBlock c ext)) mk
    }

instance StowableLedgerTables (LedgerState (SimpleBlock c ext)) where
  stowLedgerTables     s = s { simpleLedgerState = simpleLedgerState s { mockUtxo = ... simpleLedgerTables s }
                             , simpleLedgerTables = ApplyEmptyMK } 
  unstowLedgerTables s = s { simpleLedgerState = simpleLedgerState s { mockUtxo = mempty }
                             , simpleLedgerTables = ApplyValuesMK $ DS.Values $ mockUtxo $ simpleLedgerState s } 
```

**Comment by dnadales** [comment]
Some thoughts:

> As there are no blocks from the point of view of the mempool, it treats single transactions as full blocks and just increment the slot and rehash it (see applyTxToLedger)

Maybe we want to define actions that update the ledger state completely. This is more abstract and would help us when testing UTxO HD.


> After each test, check that the contents of the mempool are valid plus the property being tested (see end of setupAndRun)

Do we check that the mempool is updated as we expect? If so, this would play the role of "testing against a model". However, if we have to define a model to cover the parallel execution of the mempool maybe we will need a state machine model anyway.


> Do we want to test more in the sequential case?

I think so.

> Is there a way to adapt this to the parallel case?

Here I'd lean towards using QSM, since testing in parallel is not trivial.

> The generators take as base ledger testInitLedger but it could be adapted to take an already generated ledger so that we can build chains of setups which can translate in chains of actions. 

Yeah, that'd be my preference as well.

> This also opened a question. Should we modify the mock ledger to be able to work with tables?

We should look at what I've done here: https://github.com/input-output-hk/ouroboros-network/pull/4176/files, maybe we can use the `TestBlock` that is parametric on the payload. I also wonder if it'd make sense to write properties that are parametrized over blocks. This would allow us, if needed, to instantiate the mempool with different kind of blocks.

**Comment by Jasagredo** [comment]
Will be closed by 
- [ ] #4076
- [x] #4184
