### ISSUE TITLE
UTxO-HD prototype benchmarking

### ISSUE THREAD

**Issue by Jasagredo** [input-output-hk/ouroboros-network#4210]
- [ ] input-output-hk/cardano-node#4145
- [x] #4040 
- [x] Discard #3943

**Comment by dnadales** [comment]
We completed the first system-level benchmarks. There were some substantial performance regressions, but they were due to a high frequency of ledger snapshots combined with a coarse-grained locking mechanism. Since UTxO HD taking snapshots involve locking the ledger state and more IO, so the unrealistic snapshotting policy was not a problem before this feature.

After introducing a [finer locking mechanism](https://github.com/input-output-hk/ouroboros-network/issues/4393) we will run the second round of system-level benchmarks.
