### ISSUE TITLE
Implement PBFT chain selection rule

### ISSUE THREAD

**Issue by nc6** [input-output-hk/ouroboros-network#422]
Currently PBFT just uses the default chain selection method and compares on length.

**Comment by edsko** [comment]
Let's just remove that `default`. It was ill-advised. (Who wrote that :angry: :grin: )

**Comment by nc6** [comment]
Actually this is probably fine. We clarified that PBFT chain selection is the same as BFT selection.

Background: https://input-output-rnd.slack.com/archives/GCW2S19CM/p1557308358111600

Leaving this ticket open for the moment, but I think ultimately we can remove it.

**Comment by edsko** [comment]
So this is a somewhat subtle issue, but after a lengthy discussion the conclusion is that preferring chains based on length is indeed okay. It's somewhat subtle because there are subtle differences in which chains the old implementation (`cardano-sl`) and the new implementation consider valid; the new implementation considers some chains valid that would be rejected by the old (specifically, if an older cert is used for a particular key); in this case the old codebase might reject a longer chain that would not be rejected by the new codebase. However, we will not normally construct a new certificate for the same key, and so this is considered an acceptable risk. Details at https://input-output-rnd.slack.com/archives/CCZSDE005/p1558683130001000 . Closing this issue.
