### ISSUE TITLE
Immutable DB does not support incremental decoders

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#501]
The Immutable DB reads blocks in their entirety before returning them to the caller, making it impossible to use incremental decoders. 

Note that returning un-evaluated lazy bytestrings is _not_ the answer here (looking at you @dcoutts :D ) . 

Related: #384.

**Comment by mrBliss** [comment]
The same solution could be applied to the Volatile DB.

**Comment by mrBliss** [comment]
#2514 and #2513 will allow the ImmutableDB and VolatileDB to do the decoding themselves instead of just returning the blocks as bytestring.

However, a block decoder has type `forall s. Decoder s (Lazy.ByteString -> blk)`, which means we need to retain the bytestring corresponding to the entire block anyway so we can pass it to the result of the decoder. Moreover, I'm pretty sure that blocks are read in a single chunk anyway (only in case of partial reads would we get multiple chunks). So I don't think there's much to gain here.

Therefore I'm closing this issue.
