### ISSUE TITLE
Reconsider `UpdateLedger`

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#596]
It is not entirely clear to me at present why we need a separate `applyLedgerHeader` and `applyLedgerBlock`. We should reconsider this and discuss it with @nc6.

**Comment by nc6** [comment]
Let me write down a justification here, then we can consider whether it's strong enough to keep this separation.

We can break down the processing on receiving a block into three distinct phases:

1. Processing pertaining to the ledger which uses only the content of the header (or, in most cases, only the slot number of the block)
2. Processing pertaining to the protocol, which uses only the header.
3. Processing related to the ledger using the full content of the block.

There is one ordering constraint here, which is that 1 must happen before 2. The separate `applyLedgerHeader` and `applyLedgerBlock` functions allow us to keep the sequence 1,2,3. However, we could merge these if we instead did 1,3,2

I don't think there's any technical reason not to do this. However, my intuition definitely prefers the 1,2,3 ordering, because it would seem to more closely model how we think about block processing - that we process the container before the payload. Such an ordering (once the `BlockHeader` type exists) would also demonstrate a desired constraint in the system - that the protocol header processing cannot depend on any part of the block body.

**Comment by edsko** [comment]
Ok, that seems reasonable. I don't think there is much to do with this ticket then, except we might want to move some of the above to the documentation of `UpdateLedger`.

Mind that as part of #616 I already changed the types so that 1, 2 only get the header, not the whole block.

**Comment by ruhatch** [comment]
This was changed as part of #848.

We restructured the entry point sequence to include a new `applyChainTick` that handles changes between slots, but before processing the block. This leaves us with:
- `applyChainTick` 
- `applyLedgerBlock` (which now includes header processing)
- `applyChainState`
