### ISSUE TITLE
Shelley update system logging requirements

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/ouroboros-network#606]
# What

This issue is intended to serve as an assembly point for the update system logging requirements.

# Principles

The update system machinery mediates evolution of the blockchain, and so importance of visibility of its operation appears hard to overstate.  For this reason we chose to trace the entire scope of update system state changes and auxiliary messaging.

# What to log

  1. Client-to-node submission of a proposal/vote, including node's validity assessment.
  2. Proposal/vote admission into mempool, including, in particular, the update proposal ID.
  3. Node transmission/receipt of proposals/votes via inter-node mempool-sync protocol.
  4. Minting of a proposal/vote into a block.
  5. Node's update system state transitions:
     1. proposal/vote registration, including details of validity assessment
     2. proposal confirmation
     3. proposal endorsement
     4. proposal exceeding their TTL
  6. Turn-of-epoch changes taking effect due to endorsed proposals.
  7. Periodic update system state printouts, for human inspection purposes
     (hourly?):
     - outstanding votes and proposals, with remaining TTL.

# Open questions
  1. Should we take effort to deanonymise clients submitting the proposals/votes -- at least in the logs?

**Comment by jbgi** [comment]
:+1:

**Comment by dcoutts** [comment]
> Client-to-node submission of a proposal/vote, including node's validity assessment.
> Node signing of a proposal/vote and their admission into mempool.
    Node transmission/receipt of proposals/votes via inter-node mempool-sync protocol.
    Minting of a proposal/vote into a block.
    Node's update system state transitions:
        proposal/vote registration, including details of validity assessment
        proposal confirmation
        proposal endorsement
        proposal exceeding their TTL
    Turn-of-epoch changes taking effect due to endorsed proposals.
    Periodic update system state printouts, for human inspection purposes
    (hourly?):
        outstanding votes and proposals, with remaining TTL.

**Comment by deepfire** [comment]
Replying just to the controversial parts:

> Hmm? Nodes do not sign proposals/votes. They're signed offline and submitted to a node.

Good point!  That's not how it's currently implemented in `demo/update-system`, though, because the keys never hit offline storage in `demo-playground`.

> Do you really want that? If we have trace points on state changes then it should be possible to have a monitor that can report the current state at any time.

Yes, operationally that would be very useful, since it would eliminate a lot of guesswork for operators, who don't necessarily have a clear picture of how things work.

Thanks a lot!

**Comment by dcoutts** [comment]
> > > Periodic update system state printouts, for human inspection purposes (hourly?):
outstanding votes and proposals, with remaining TTL.

> > Do you really want that? If we have trace points on state changes then it should be possible to have a monitor that can report the current state at any time.

> Yes, operationally that would be very useful, since it would eliminate a lot of guesswork for operators, who don't necessarily have a clear picture of how things work.

The same logic applies to any slowly changing state. An EKG label can report the current state, and that can be forwarded on to statsd or any other system that can handle label/text style metrics. So operators can just look at the monitoring system for the current state.

Remember, it is not stake pool operators who submit update proposals or votes.

**Comment by edsko** [comment]
Marking this as high priority since _some_ logging will be needed for the testnet to be useful at all; however, we can probably release (even mainnet) without implementing quite all of the above.

**Comment by edsko** [comment]
[x] Client-to-node submission of a proposal/vote, including node's validity assessment.
[x] Proposal/vote admission into mempool, including, in particular, the update proposal ID.

The _submission_ of the transaction is logged as part of the client-to-node submission protocol (see `ptLocalTxSubmissionTracer`), as per Duncan's comments above. The node's validity assessment can be derived from the logging of the mempool (`TraceMempoolAddedTx`, `TraceMempoolRejectedTx`), which will log the entire transaction, including IDs.

[x] Node transmission/receipt of proposals/votes via inter-node mempool-sync protocol.

The mempool logging is independent from the submission route. Node-to-node communication is traced as part of the protocol tracing, as per Duncan's comments (see `ptTxSubmissionTracer`).

[x] Minting of a proposal/vote into a block.

We log the full block that we produce, see `TraceForgedBlock`.

[x] Node's update system state transitions: (1) proposal/vote registration, including details of validity assessment, (2) proposal confirmation, (3) proposal endorsement, (4) proposal exceeding their TTL

There is a tracer called `cdbTraceLedger`, which traces all changes to the ledger DB, which in turn gives you the `k` most recent ledger states, and in particular, the most recent one (`ledgerDbCurrent`). From this all of the above should be derivable. 

[x] Turn-of-epoch changes taking effect due to endorsed proposals.

This is also just a ledger rule, and so previous comment applies.

[x] Periodic update system state printouts, for human inspection purposes (hourly?): outstanding votes and proposals, with remaining TTL.

The ledger DB tracing gives you access to the ledger DB state. If you really did want to print something periodically, you don't need support from consensus for that. Note that "remaining TTL" can be derived from changes to the ledger (previous point).
