### ISSUE TITLE
Include mock EBBs

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-network#966]
As #872, except for `test-consensus` instead of `test-storage`. Likely useful overlap between the two.

This Issue partly represents the obligation to write a more specific test for PR #951 (Issue #925).

**Comment by edsko** [comment]
Calling this low priority because we already know that we can sync the existing chain, and those are the only EBBs that will ever be in existence.

**Comment by mrBliss** [comment]
Currently, only in the `RealPBFT` protocol test do we generate an EBB, and only one: the Genesis EBB, which is forged whenever the leader has an empty chain.

#1313 contains a possible approach to generating EBBs for all epochs, just like in the old mainnet. Some things still need to be done, quoting @nfrisby:

* Race condition between that new thread and the forging.
* Also, some of the properties and the idealized RealPBFT simulator may need to be updated to no longer assume that a node leading in its join slot always forges the 0-EBB and only the 0-EBB.
* Lastly, it's somewhat confusing that the block producer thread may generate the 0-EBB (since that's defined as part of `forgeByronBlock` in `ouroboros-consensus:lib`) while all the others come from the test infrastructure.

**Comment by mrBliss** [comment]
> Currently, only in the `RealPBFT` protocol test do we generate an EBB, and only one: the Genesis EBB, which is forged whenever the leader has an empty chain.
> 
> #1313 contains a possible approach to generating EBBs for all epochs, just like in the old mainnet. Some things still need to be done, quoting @nfrisby:
> 
>     * Race condition between that new thread and the forging.
> 
>     * Also, some of the properties and the idealized RealPBFT simulator may need to be updated to no longer assume that a node leading in its join slot always forges the 0-EBB and only the 0-EBB.
> 
>     * Lastly, it's somewhat confusing that the block producer thread may generate the 0-EBB (since that's defined as part of `forgeByronBlock` in `ouroboros-consensus:lib`) while all the others come from the test infrastructure.

For now, I think the best course of action is to pursue this approach (generate an EBB in each epoch for `RealPBFT`) instead of extending the mock blocks with EBBs.

**Comment by nfrisby** [comment]
Just a note: During development of these tests, we found Issue 1339, which Thomas promptly fixed with PR 1440.
